{ %CPU=x86_64 }
{ %OPT=-O3 }
program tfoldruntimereal1;

{ A floating-point operation on constants met after inlining is a run-time
  operation.  Where the compiler folds it, the value is bit for bit the one the
  instruction computes at run time in the product FP state (round to nearest,
  exceptions masked); an operation with an exceptional operand or result stays
  at run time and traps once the program unmasks the exception.  A result that
  rounds up to the smallest normal number is tiny (x86 detects tininess after
  rounding) and underflows: it stays at run time too.

  Every inline helper is called with grid constants (folded where ordinary) and,
  inside a routine that is not inlined, with the same values as parameters
  (computed at run time); reals are compared by bits, NaN payload and the sign
  of zero included.  P1*P2 and 1+H are halfway cases: computed in the x87
  format and rounded to Double afterwards they come out one unit lower than
  the SSE instruction gives.  Min/max over an array element and over a field
  through a pointer (the rewrite into minsd/maxsd) is compared with a form the
  rewrite does not touch.  The same program compiles under Delphi 12.2.
  It sets no range or overflow switch: the real-folds gate also builds it
  with -Cr -Co, where the min/max over an element keeps its range check.

  Generated by lab/impl/real_numbers_after_inline/gen/gen_test.py (the
  generator wrote the Q- and R- switches, taken out here). }

{$ifdef FPC}
  {$mode delphi}
{$endif}
{$APPTYPE CONSOLE}

uses
  SysUtils, Math;

type
  TRange = record
    Lo, Hi: Double;
  end;
  PRange = ^TRange;

var
  Checks, Failures: Integer;

function DBits(X: Double): UInt64;
begin
  Move(X, Result, SizeOf(Result));
end;

function SBits(X: Single): Cardinal;
begin
  Move(X, Result, SizeOf(Result));
end;

procedure Fail(const What: string);
begin
  Inc(Failures);
  WriteLn('MISMATCH ', What);
end;

procedure CD(Code: Integer; Folded, Runtime: Double);
begin
  Inc(Checks);
  If DBits(Folded) <> DBits(Runtime) then
    Fail(IntToStr(Code) + ' folded=' + IntToHex(DBits(Folded), 16) + ' run-time=' + IntToHex(DBits(Runtime), 16));
end;

procedure CS(Code: Integer; Folded, Runtime: Single);
begin
  Inc(Checks);
  If SBits(Folded) <> SBits(Runtime) then
    Fail(IntToStr(Code) + ' folded=' + IntToHex(SBits(Folded), 8) + ' run-time=' + IntToHex(SBits(Runtime), 8));
end;

procedure CB(Code: Integer; Folded, Runtime: Boolean);
begin
  Inc(Checks);
  If Folded <> Runtime then
    Fail(IntToStr(Code) + ' folded=' + BoolToStr(Folded, True) + ' run-time=' + BoolToStr(Runtime, True));
end;

procedure CI(Code: Integer; Folded, Runtime: Int64);
begin
  Inc(Checks);
  If Folded <> Runtime then
    Fail(IntToStr(Code) + ' folded=' + IntToStr(Folded) + ' run-time=' + IntToStr(Runtime));
end;

function AddD(A, B: Double): Double; inline; begin Result := A + B; end;
function SubD(A, B: Double): Double; inline; begin Result := A - B; end;
function MulD(A, B: Double): Double; inline; begin Result := A * B; end;
function DivD(A, B: Double): Double; inline; begin Result := A / B; end;
function LtD(A, B: Double): Boolean; inline; begin Result := A < B; end;
function LeD(A, B: Double): Boolean; inline; begin Result := A <= B; end;
function GtD(A, B: Double): Boolean; inline; begin Result := A > B; end;
function GeD(A, B: Double): Boolean; inline; begin Result := A >= B; end;
function EqD(A, B: Double): Boolean; inline; begin Result := A = B; end;
function NeD(A, B: Double): Boolean; inline; begin Result := A <> B; end;
function MinD(A, B: Double): Double; inline; begin Result := Min(A, B); end;
function MaxD(A, B: Double): Double; inline; begin Result := Max(A, B); end;
function SqrD(A: Double): Double; inline; begin Result := Sqr(A); end;
function SqrtD(A: Double): Double; inline; begin Result := Sqrt(A); end;
function FracD(A: Double): Double; inline; begin Result := Frac(A); end;
function IntD(A: Double): Double; inline; begin Result := Int(A); end;
function ExpD(A: Double): Double; inline; begin Result := Exp(A); end;
function LnD(A: Double): Double; inline; begin Result := Ln(A); end;
function SinD(A: Double): Double; inline; begin Result := Sin(A); end;
function CosD(A: Double): Double; inline; begin Result := Cos(A); end;
function ArcTanD(A: Double): Double; inline; begin Result := ArcTan(A); end;
function AbsD(A: Double): Double; inline; begin Result := Abs(A); end;
function TruncD(A: Double): Int64; inline; begin Result := Trunc(A); end;
function DToS(A: Double): Single; inline; begin Result := A; end;

function AddS(A, B: Single): Single; inline; begin Result := A + B; end;
function SubS(A, B: Single): Single; inline; begin Result := A - B; end;
function MulS(A, B: Single): Single; inline; begin Result := A * B; end;
function DivS(A, B: Single): Single; inline; begin Result := A / B; end;
function LtS(A, B: Single): Boolean; inline; begin Result := A < B; end;
function EqS(A, B: Single): Boolean; inline; begin Result := A = B; end;
function MinS(A, B: Single): Single; inline; begin Result := Min(A, B); end;
function MaxS(A, B: Single): Single; inline; begin Result := Max(A, B); end;
function SqrS(A: Single): Single; inline; begin Result := Sqr(A); end;
function SqrtS(A: Single): Single; inline; begin Result := Sqrt(A); end;
function SToD(A: Single): Double; inline; begin Result := A; end;

procedure PairD(Code: Integer; A, B, FAdd, FSub, FMul, FDiv: Double;
  FLt, FLe, FGt, FGe, FEq, FNe: Boolean; FMin, FMax: Double); {$ifdef FPC}noinline;{$endif}
begin
  CD(Code + 0, FAdd, AddD(A, B));
  CD(Code + 1, FSub, SubD(A, B));
  CD(Code + 2, FMul, MulD(A, B));
  CD(Code + 3, FDiv, DivD(A, B));
  CB(Code + 4, FLt, LtD(A, B));
  CB(Code + 5, FLe, LeD(A, B));
  CB(Code + 6, FGt, GtD(A, B));
  CB(Code + 7, FGe, GeD(A, B));
  CB(Code + 8, FEq, EqD(A, B));
  CB(Code + 9, FNe, NeD(A, B));
  CD(Code + 10, FMin, MinD(A, B));
  CD(Code + 11, FMax, MaxD(A, B));
end;

procedure UnaryD(Code: Integer; A, FSqr, FSqrt, FFrac, FInt, FExp, FLn, FSin, FCos, FArcTan, FAbs: Double;
  FTrunc: Int64; FToS: Single); {$ifdef FPC}noinline;{$endif}
begin
  CD(Code + 0, FSqr, SqrD(A));
  CD(Code + 1, FSqrt, SqrtD(A));
  CD(Code + 2, FFrac, FracD(A));
  CD(Code + 3, FInt, IntD(A));
  CD(Code + 4, FExp, ExpD(A));
  CD(Code + 5, FLn, LnD(A));
  CD(Code + 6, FSin, SinD(A));
  CD(Code + 7, FCos, CosD(A));
  CD(Code + 8, FArcTan, ArcTanD(A));
  CD(Code + 9, FAbs, AbsD(A));
  { Trunc of a NaN, an infinity or a value outside Int64 is the integer
    indefinite at run time: compare only where it is defined }
  If not IsNan(A) and (Abs(A) < 9.2e18) then
    CI(Code + 10, FTrunc, TruncD(A));
  CS(Code + 11, FToS, DToS(A));
end;

procedure PairS(Code: Integer; A, B, FAdd, FSub, FMul, FDiv: Single; FLt, FEq: Boolean;
  FMin, FMax: Single); {$ifdef FPC}noinline;{$endif}
begin
  CS(Code + 0, FAdd, AddS(A, B));
  CS(Code + 1, FSub, SubS(A, B));
  CS(Code + 2, FMul, MulS(A, B));
  CS(Code + 3, FDiv, DivS(A, B));
  CB(Code + 4, FLt, LtS(A, B));
  CB(Code + 5, FEq, EqS(A, B));
  CS(Code + 6, FMin, MinS(A, B));
  CS(Code + 7, FMax, MaxS(A, B));
end;

procedure UnaryS(Code: Integer; A, FSqr, FSqrt: Single; FToD: Double); {$ifdef FPC}noinline;{$endif}
begin
  CS(Code + 0, FSqr, SqrS(A));
  CS(Code + 1, FSqrt, SqrtS(A));
  CD(Code + 2, FToD, SToD(A));
end;

const
  D00 = 0.0; { +0 }
  D01 = -0.0; { -0 }
  D02 = 1.0; { 1 }
  D03 = -1.0; { -1 }
  D04 = 1.5; { 1.5 }
  D05 = 0.1; { 0.1 }
  D06 = 3.0; { 3 }
  D07 = 1.7976931348623157e308; { MaxDouble }
  D08 = 2.2250738585072014e-308; { MinNormal }
  D09 = 4.9406564584124654e-324; { MinSubnormal }
  D10 = Infinity; { +Inf }
  D11 = NegInfinity; { -Inf }
  D12 = NaN; { NaN }
  D13 = 1.0977456781970063; { P1 }
  D14 = 1.4521756245746542; { P2 }
  D15 = 1.1102230328969627e-16; { H }
  S00 = Single(0.0); { +0 }
  S01 = Single(-0.0); { -0 }
  S02 = Single(1.0); { 1 }
  S03 = Single(-1.0); { -1 }
  S04 = Single(1.5); { 1.5 }
  S05 = Single(0.1); { 0.1 }
  S06 = Single(3.0); { 3 }
  S07 = Single(3.4028234663852886e38); { MaxSingle }
  S08 = Single(1.1754943508222875e-38); { MinNormal }
  S09 = Single(1.4012984643248171e-45); { MinSubnormal }
  S10 = Single(Infinity); { +Inf }
  S11 = Single(NaN); { NaN }

procedure RunPairsD;
begin
  PairD(100000, D00, D00, AddD(D00, D00), SubD(D00, D00), MulD(D00, D00), DivD(D00, D00), LtD(D00, D00), LeD(D00, D00), GtD(D00, D00), GeD(D00, D00), EqD(D00, D00), NeD(D00, D00), MinD(D00, D00), MaxD(D00, D00));
  PairD(100100, D00, D01, AddD(D00, D01), SubD(D00, D01), MulD(D00, D01), DivD(D00, D01), LtD(D00, D01), LeD(D00, D01), GtD(D00, D01), GeD(D00, D01), EqD(D00, D01), NeD(D00, D01), MinD(D00, D01), MaxD(D00, D01));
  PairD(100200, D00, D02, AddD(D00, D02), SubD(D00, D02), MulD(D00, D02), DivD(D00, D02), LtD(D00, D02), LeD(D00, D02), GtD(D00, D02), GeD(D00, D02), EqD(D00, D02), NeD(D00, D02), MinD(D00, D02), MaxD(D00, D02));
  PairD(100300, D00, D03, AddD(D00, D03), SubD(D00, D03), MulD(D00, D03), DivD(D00, D03), LtD(D00, D03), LeD(D00, D03), GtD(D00, D03), GeD(D00, D03), EqD(D00, D03), NeD(D00, D03), MinD(D00, D03), MaxD(D00, D03));
  PairD(100400, D00, D04, AddD(D00, D04), SubD(D00, D04), MulD(D00, D04), DivD(D00, D04), LtD(D00, D04), LeD(D00, D04), GtD(D00, D04), GeD(D00, D04), EqD(D00, D04), NeD(D00, D04), MinD(D00, D04), MaxD(D00, D04));
  PairD(100500, D00, D05, AddD(D00, D05), SubD(D00, D05), MulD(D00, D05), DivD(D00, D05), LtD(D00, D05), LeD(D00, D05), GtD(D00, D05), GeD(D00, D05), EqD(D00, D05), NeD(D00, D05), MinD(D00, D05), MaxD(D00, D05));
  PairD(100600, D00, D06, AddD(D00, D06), SubD(D00, D06), MulD(D00, D06), DivD(D00, D06), LtD(D00, D06), LeD(D00, D06), GtD(D00, D06), GeD(D00, D06), EqD(D00, D06), NeD(D00, D06), MinD(D00, D06), MaxD(D00, D06));
  PairD(100700, D00, D07, AddD(D00, D07), SubD(D00, D07), MulD(D00, D07), DivD(D00, D07), LtD(D00, D07), LeD(D00, D07), GtD(D00, D07), GeD(D00, D07), EqD(D00, D07), NeD(D00, D07), MinD(D00, D07), MaxD(D00, D07));
  PairD(100800, D00, D08, AddD(D00, D08), SubD(D00, D08), MulD(D00, D08), DivD(D00, D08), LtD(D00, D08), LeD(D00, D08), GtD(D00, D08), GeD(D00, D08), EqD(D00, D08), NeD(D00, D08), MinD(D00, D08), MaxD(D00, D08));
  PairD(100900, D00, D09, AddD(D00, D09), SubD(D00, D09), MulD(D00, D09), DivD(D00, D09), LtD(D00, D09), LeD(D00, D09), GtD(D00, D09), GeD(D00, D09), EqD(D00, D09), NeD(D00, D09), MinD(D00, D09), MaxD(D00, D09));
  PairD(101000, D00, D10, AddD(D00, D10), SubD(D00, D10), MulD(D00, D10), DivD(D00, D10), LtD(D00, D10), LeD(D00, D10), GtD(D00, D10), GeD(D00, D10), EqD(D00, D10), NeD(D00, D10), MinD(D00, D10), MaxD(D00, D10));
  PairD(101100, D00, D11, AddD(D00, D11), SubD(D00, D11), MulD(D00, D11), DivD(D00, D11), LtD(D00, D11), LeD(D00, D11), GtD(D00, D11), GeD(D00, D11), EqD(D00, D11), NeD(D00, D11), MinD(D00, D11), MaxD(D00, D11));
  PairD(101200, D00, D12, AddD(D00, D12), SubD(D00, D12), MulD(D00, D12), DivD(D00, D12), LtD(D00, D12), LeD(D00, D12), GtD(D00, D12), GeD(D00, D12), EqD(D00, D12), NeD(D00, D12), MinD(D00, D12), MaxD(D00, D12));
  PairD(101300, D00, D13, AddD(D00, D13), SubD(D00, D13), MulD(D00, D13), DivD(D00, D13), LtD(D00, D13), LeD(D00, D13), GtD(D00, D13), GeD(D00, D13), EqD(D00, D13), NeD(D00, D13), MinD(D00, D13), MaxD(D00, D13));
  PairD(101400, D00, D14, AddD(D00, D14), SubD(D00, D14), MulD(D00, D14), DivD(D00, D14), LtD(D00, D14), LeD(D00, D14), GtD(D00, D14), GeD(D00, D14), EqD(D00, D14), NeD(D00, D14), MinD(D00, D14), MaxD(D00, D14));
  PairD(101500, D00, D15, AddD(D00, D15), SubD(D00, D15), MulD(D00, D15), DivD(D00, D15), LtD(D00, D15), LeD(D00, D15), GtD(D00, D15), GeD(D00, D15), EqD(D00, D15), NeD(D00, D15), MinD(D00, D15), MaxD(D00, D15));
  PairD(110000, D01, D00, AddD(D01, D00), SubD(D01, D00), MulD(D01, D00), DivD(D01, D00), LtD(D01, D00), LeD(D01, D00), GtD(D01, D00), GeD(D01, D00), EqD(D01, D00), NeD(D01, D00), MinD(D01, D00), MaxD(D01, D00));
  PairD(110100, D01, D01, AddD(D01, D01), SubD(D01, D01), MulD(D01, D01), DivD(D01, D01), LtD(D01, D01), LeD(D01, D01), GtD(D01, D01), GeD(D01, D01), EqD(D01, D01), NeD(D01, D01), MinD(D01, D01), MaxD(D01, D01));
  PairD(110200, D01, D02, AddD(D01, D02), SubD(D01, D02), MulD(D01, D02), DivD(D01, D02), LtD(D01, D02), LeD(D01, D02), GtD(D01, D02), GeD(D01, D02), EqD(D01, D02), NeD(D01, D02), MinD(D01, D02), MaxD(D01, D02));
  PairD(110300, D01, D03, AddD(D01, D03), SubD(D01, D03), MulD(D01, D03), DivD(D01, D03), LtD(D01, D03), LeD(D01, D03), GtD(D01, D03), GeD(D01, D03), EqD(D01, D03), NeD(D01, D03), MinD(D01, D03), MaxD(D01, D03));
  PairD(110400, D01, D04, AddD(D01, D04), SubD(D01, D04), MulD(D01, D04), DivD(D01, D04), LtD(D01, D04), LeD(D01, D04), GtD(D01, D04), GeD(D01, D04), EqD(D01, D04), NeD(D01, D04), MinD(D01, D04), MaxD(D01, D04));
  PairD(110500, D01, D05, AddD(D01, D05), SubD(D01, D05), MulD(D01, D05), DivD(D01, D05), LtD(D01, D05), LeD(D01, D05), GtD(D01, D05), GeD(D01, D05), EqD(D01, D05), NeD(D01, D05), MinD(D01, D05), MaxD(D01, D05));
  PairD(110600, D01, D06, AddD(D01, D06), SubD(D01, D06), MulD(D01, D06), DivD(D01, D06), LtD(D01, D06), LeD(D01, D06), GtD(D01, D06), GeD(D01, D06), EqD(D01, D06), NeD(D01, D06), MinD(D01, D06), MaxD(D01, D06));
  PairD(110700, D01, D07, AddD(D01, D07), SubD(D01, D07), MulD(D01, D07), DivD(D01, D07), LtD(D01, D07), LeD(D01, D07), GtD(D01, D07), GeD(D01, D07), EqD(D01, D07), NeD(D01, D07), MinD(D01, D07), MaxD(D01, D07));
  PairD(110800, D01, D08, AddD(D01, D08), SubD(D01, D08), MulD(D01, D08), DivD(D01, D08), LtD(D01, D08), LeD(D01, D08), GtD(D01, D08), GeD(D01, D08), EqD(D01, D08), NeD(D01, D08), MinD(D01, D08), MaxD(D01, D08));
  PairD(110900, D01, D09, AddD(D01, D09), SubD(D01, D09), MulD(D01, D09), DivD(D01, D09), LtD(D01, D09), LeD(D01, D09), GtD(D01, D09), GeD(D01, D09), EqD(D01, D09), NeD(D01, D09), MinD(D01, D09), MaxD(D01, D09));
  PairD(111000, D01, D10, AddD(D01, D10), SubD(D01, D10), MulD(D01, D10), DivD(D01, D10), LtD(D01, D10), LeD(D01, D10), GtD(D01, D10), GeD(D01, D10), EqD(D01, D10), NeD(D01, D10), MinD(D01, D10), MaxD(D01, D10));
  PairD(111100, D01, D11, AddD(D01, D11), SubD(D01, D11), MulD(D01, D11), DivD(D01, D11), LtD(D01, D11), LeD(D01, D11), GtD(D01, D11), GeD(D01, D11), EqD(D01, D11), NeD(D01, D11), MinD(D01, D11), MaxD(D01, D11));
  PairD(111200, D01, D12, AddD(D01, D12), SubD(D01, D12), MulD(D01, D12), DivD(D01, D12), LtD(D01, D12), LeD(D01, D12), GtD(D01, D12), GeD(D01, D12), EqD(D01, D12), NeD(D01, D12), MinD(D01, D12), MaxD(D01, D12));
  PairD(111300, D01, D13, AddD(D01, D13), SubD(D01, D13), MulD(D01, D13), DivD(D01, D13), LtD(D01, D13), LeD(D01, D13), GtD(D01, D13), GeD(D01, D13), EqD(D01, D13), NeD(D01, D13), MinD(D01, D13), MaxD(D01, D13));
  PairD(111400, D01, D14, AddD(D01, D14), SubD(D01, D14), MulD(D01, D14), DivD(D01, D14), LtD(D01, D14), LeD(D01, D14), GtD(D01, D14), GeD(D01, D14), EqD(D01, D14), NeD(D01, D14), MinD(D01, D14), MaxD(D01, D14));
  PairD(111500, D01, D15, AddD(D01, D15), SubD(D01, D15), MulD(D01, D15), DivD(D01, D15), LtD(D01, D15), LeD(D01, D15), GtD(D01, D15), GeD(D01, D15), EqD(D01, D15), NeD(D01, D15), MinD(D01, D15), MaxD(D01, D15));
  PairD(120000, D02, D00, AddD(D02, D00), SubD(D02, D00), MulD(D02, D00), DivD(D02, D00), LtD(D02, D00), LeD(D02, D00), GtD(D02, D00), GeD(D02, D00), EqD(D02, D00), NeD(D02, D00), MinD(D02, D00), MaxD(D02, D00));
  PairD(120100, D02, D01, AddD(D02, D01), SubD(D02, D01), MulD(D02, D01), DivD(D02, D01), LtD(D02, D01), LeD(D02, D01), GtD(D02, D01), GeD(D02, D01), EqD(D02, D01), NeD(D02, D01), MinD(D02, D01), MaxD(D02, D01));
  PairD(120200, D02, D02, AddD(D02, D02), SubD(D02, D02), MulD(D02, D02), DivD(D02, D02), LtD(D02, D02), LeD(D02, D02), GtD(D02, D02), GeD(D02, D02), EqD(D02, D02), NeD(D02, D02), MinD(D02, D02), MaxD(D02, D02));
  PairD(120300, D02, D03, AddD(D02, D03), SubD(D02, D03), MulD(D02, D03), DivD(D02, D03), LtD(D02, D03), LeD(D02, D03), GtD(D02, D03), GeD(D02, D03), EqD(D02, D03), NeD(D02, D03), MinD(D02, D03), MaxD(D02, D03));
  PairD(120400, D02, D04, AddD(D02, D04), SubD(D02, D04), MulD(D02, D04), DivD(D02, D04), LtD(D02, D04), LeD(D02, D04), GtD(D02, D04), GeD(D02, D04), EqD(D02, D04), NeD(D02, D04), MinD(D02, D04), MaxD(D02, D04));
  PairD(120500, D02, D05, AddD(D02, D05), SubD(D02, D05), MulD(D02, D05), DivD(D02, D05), LtD(D02, D05), LeD(D02, D05), GtD(D02, D05), GeD(D02, D05), EqD(D02, D05), NeD(D02, D05), MinD(D02, D05), MaxD(D02, D05));
  PairD(120600, D02, D06, AddD(D02, D06), SubD(D02, D06), MulD(D02, D06), DivD(D02, D06), LtD(D02, D06), LeD(D02, D06), GtD(D02, D06), GeD(D02, D06), EqD(D02, D06), NeD(D02, D06), MinD(D02, D06), MaxD(D02, D06));
  PairD(120700, D02, D07, AddD(D02, D07), SubD(D02, D07), MulD(D02, D07), DivD(D02, D07), LtD(D02, D07), LeD(D02, D07), GtD(D02, D07), GeD(D02, D07), EqD(D02, D07), NeD(D02, D07), MinD(D02, D07), MaxD(D02, D07));
  PairD(120800, D02, D08, AddD(D02, D08), SubD(D02, D08), MulD(D02, D08), DivD(D02, D08), LtD(D02, D08), LeD(D02, D08), GtD(D02, D08), GeD(D02, D08), EqD(D02, D08), NeD(D02, D08), MinD(D02, D08), MaxD(D02, D08));
  PairD(120900, D02, D09, AddD(D02, D09), SubD(D02, D09), MulD(D02, D09), DivD(D02, D09), LtD(D02, D09), LeD(D02, D09), GtD(D02, D09), GeD(D02, D09), EqD(D02, D09), NeD(D02, D09), MinD(D02, D09), MaxD(D02, D09));
  PairD(121000, D02, D10, AddD(D02, D10), SubD(D02, D10), MulD(D02, D10), DivD(D02, D10), LtD(D02, D10), LeD(D02, D10), GtD(D02, D10), GeD(D02, D10), EqD(D02, D10), NeD(D02, D10), MinD(D02, D10), MaxD(D02, D10));
  PairD(121100, D02, D11, AddD(D02, D11), SubD(D02, D11), MulD(D02, D11), DivD(D02, D11), LtD(D02, D11), LeD(D02, D11), GtD(D02, D11), GeD(D02, D11), EqD(D02, D11), NeD(D02, D11), MinD(D02, D11), MaxD(D02, D11));
  PairD(121200, D02, D12, AddD(D02, D12), SubD(D02, D12), MulD(D02, D12), DivD(D02, D12), LtD(D02, D12), LeD(D02, D12), GtD(D02, D12), GeD(D02, D12), EqD(D02, D12), NeD(D02, D12), MinD(D02, D12), MaxD(D02, D12));
  PairD(121300, D02, D13, AddD(D02, D13), SubD(D02, D13), MulD(D02, D13), DivD(D02, D13), LtD(D02, D13), LeD(D02, D13), GtD(D02, D13), GeD(D02, D13), EqD(D02, D13), NeD(D02, D13), MinD(D02, D13), MaxD(D02, D13));
  PairD(121400, D02, D14, AddD(D02, D14), SubD(D02, D14), MulD(D02, D14), DivD(D02, D14), LtD(D02, D14), LeD(D02, D14), GtD(D02, D14), GeD(D02, D14), EqD(D02, D14), NeD(D02, D14), MinD(D02, D14), MaxD(D02, D14));
  PairD(121500, D02, D15, AddD(D02, D15), SubD(D02, D15), MulD(D02, D15), DivD(D02, D15), LtD(D02, D15), LeD(D02, D15), GtD(D02, D15), GeD(D02, D15), EqD(D02, D15), NeD(D02, D15), MinD(D02, D15), MaxD(D02, D15));
  PairD(130000, D03, D00, AddD(D03, D00), SubD(D03, D00), MulD(D03, D00), DivD(D03, D00), LtD(D03, D00), LeD(D03, D00), GtD(D03, D00), GeD(D03, D00), EqD(D03, D00), NeD(D03, D00), MinD(D03, D00), MaxD(D03, D00));
  PairD(130100, D03, D01, AddD(D03, D01), SubD(D03, D01), MulD(D03, D01), DivD(D03, D01), LtD(D03, D01), LeD(D03, D01), GtD(D03, D01), GeD(D03, D01), EqD(D03, D01), NeD(D03, D01), MinD(D03, D01), MaxD(D03, D01));
  PairD(130200, D03, D02, AddD(D03, D02), SubD(D03, D02), MulD(D03, D02), DivD(D03, D02), LtD(D03, D02), LeD(D03, D02), GtD(D03, D02), GeD(D03, D02), EqD(D03, D02), NeD(D03, D02), MinD(D03, D02), MaxD(D03, D02));
  PairD(130300, D03, D03, AddD(D03, D03), SubD(D03, D03), MulD(D03, D03), DivD(D03, D03), LtD(D03, D03), LeD(D03, D03), GtD(D03, D03), GeD(D03, D03), EqD(D03, D03), NeD(D03, D03), MinD(D03, D03), MaxD(D03, D03));
  PairD(130400, D03, D04, AddD(D03, D04), SubD(D03, D04), MulD(D03, D04), DivD(D03, D04), LtD(D03, D04), LeD(D03, D04), GtD(D03, D04), GeD(D03, D04), EqD(D03, D04), NeD(D03, D04), MinD(D03, D04), MaxD(D03, D04));
  PairD(130500, D03, D05, AddD(D03, D05), SubD(D03, D05), MulD(D03, D05), DivD(D03, D05), LtD(D03, D05), LeD(D03, D05), GtD(D03, D05), GeD(D03, D05), EqD(D03, D05), NeD(D03, D05), MinD(D03, D05), MaxD(D03, D05));
  PairD(130600, D03, D06, AddD(D03, D06), SubD(D03, D06), MulD(D03, D06), DivD(D03, D06), LtD(D03, D06), LeD(D03, D06), GtD(D03, D06), GeD(D03, D06), EqD(D03, D06), NeD(D03, D06), MinD(D03, D06), MaxD(D03, D06));
  PairD(130700, D03, D07, AddD(D03, D07), SubD(D03, D07), MulD(D03, D07), DivD(D03, D07), LtD(D03, D07), LeD(D03, D07), GtD(D03, D07), GeD(D03, D07), EqD(D03, D07), NeD(D03, D07), MinD(D03, D07), MaxD(D03, D07));
  PairD(130800, D03, D08, AddD(D03, D08), SubD(D03, D08), MulD(D03, D08), DivD(D03, D08), LtD(D03, D08), LeD(D03, D08), GtD(D03, D08), GeD(D03, D08), EqD(D03, D08), NeD(D03, D08), MinD(D03, D08), MaxD(D03, D08));
  PairD(130900, D03, D09, AddD(D03, D09), SubD(D03, D09), MulD(D03, D09), DivD(D03, D09), LtD(D03, D09), LeD(D03, D09), GtD(D03, D09), GeD(D03, D09), EqD(D03, D09), NeD(D03, D09), MinD(D03, D09), MaxD(D03, D09));
  PairD(131000, D03, D10, AddD(D03, D10), SubD(D03, D10), MulD(D03, D10), DivD(D03, D10), LtD(D03, D10), LeD(D03, D10), GtD(D03, D10), GeD(D03, D10), EqD(D03, D10), NeD(D03, D10), MinD(D03, D10), MaxD(D03, D10));
  PairD(131100, D03, D11, AddD(D03, D11), SubD(D03, D11), MulD(D03, D11), DivD(D03, D11), LtD(D03, D11), LeD(D03, D11), GtD(D03, D11), GeD(D03, D11), EqD(D03, D11), NeD(D03, D11), MinD(D03, D11), MaxD(D03, D11));
  PairD(131200, D03, D12, AddD(D03, D12), SubD(D03, D12), MulD(D03, D12), DivD(D03, D12), LtD(D03, D12), LeD(D03, D12), GtD(D03, D12), GeD(D03, D12), EqD(D03, D12), NeD(D03, D12), MinD(D03, D12), MaxD(D03, D12));
  PairD(131300, D03, D13, AddD(D03, D13), SubD(D03, D13), MulD(D03, D13), DivD(D03, D13), LtD(D03, D13), LeD(D03, D13), GtD(D03, D13), GeD(D03, D13), EqD(D03, D13), NeD(D03, D13), MinD(D03, D13), MaxD(D03, D13));
  PairD(131400, D03, D14, AddD(D03, D14), SubD(D03, D14), MulD(D03, D14), DivD(D03, D14), LtD(D03, D14), LeD(D03, D14), GtD(D03, D14), GeD(D03, D14), EqD(D03, D14), NeD(D03, D14), MinD(D03, D14), MaxD(D03, D14));
  PairD(131500, D03, D15, AddD(D03, D15), SubD(D03, D15), MulD(D03, D15), DivD(D03, D15), LtD(D03, D15), LeD(D03, D15), GtD(D03, D15), GeD(D03, D15), EqD(D03, D15), NeD(D03, D15), MinD(D03, D15), MaxD(D03, D15));
  PairD(140000, D04, D00, AddD(D04, D00), SubD(D04, D00), MulD(D04, D00), DivD(D04, D00), LtD(D04, D00), LeD(D04, D00), GtD(D04, D00), GeD(D04, D00), EqD(D04, D00), NeD(D04, D00), MinD(D04, D00), MaxD(D04, D00));
  PairD(140100, D04, D01, AddD(D04, D01), SubD(D04, D01), MulD(D04, D01), DivD(D04, D01), LtD(D04, D01), LeD(D04, D01), GtD(D04, D01), GeD(D04, D01), EqD(D04, D01), NeD(D04, D01), MinD(D04, D01), MaxD(D04, D01));
  PairD(140200, D04, D02, AddD(D04, D02), SubD(D04, D02), MulD(D04, D02), DivD(D04, D02), LtD(D04, D02), LeD(D04, D02), GtD(D04, D02), GeD(D04, D02), EqD(D04, D02), NeD(D04, D02), MinD(D04, D02), MaxD(D04, D02));
  PairD(140300, D04, D03, AddD(D04, D03), SubD(D04, D03), MulD(D04, D03), DivD(D04, D03), LtD(D04, D03), LeD(D04, D03), GtD(D04, D03), GeD(D04, D03), EqD(D04, D03), NeD(D04, D03), MinD(D04, D03), MaxD(D04, D03));
  PairD(140400, D04, D04, AddD(D04, D04), SubD(D04, D04), MulD(D04, D04), DivD(D04, D04), LtD(D04, D04), LeD(D04, D04), GtD(D04, D04), GeD(D04, D04), EqD(D04, D04), NeD(D04, D04), MinD(D04, D04), MaxD(D04, D04));
  PairD(140500, D04, D05, AddD(D04, D05), SubD(D04, D05), MulD(D04, D05), DivD(D04, D05), LtD(D04, D05), LeD(D04, D05), GtD(D04, D05), GeD(D04, D05), EqD(D04, D05), NeD(D04, D05), MinD(D04, D05), MaxD(D04, D05));
  PairD(140600, D04, D06, AddD(D04, D06), SubD(D04, D06), MulD(D04, D06), DivD(D04, D06), LtD(D04, D06), LeD(D04, D06), GtD(D04, D06), GeD(D04, D06), EqD(D04, D06), NeD(D04, D06), MinD(D04, D06), MaxD(D04, D06));
  PairD(140700, D04, D07, AddD(D04, D07), SubD(D04, D07), MulD(D04, D07), DivD(D04, D07), LtD(D04, D07), LeD(D04, D07), GtD(D04, D07), GeD(D04, D07), EqD(D04, D07), NeD(D04, D07), MinD(D04, D07), MaxD(D04, D07));
  PairD(140800, D04, D08, AddD(D04, D08), SubD(D04, D08), MulD(D04, D08), DivD(D04, D08), LtD(D04, D08), LeD(D04, D08), GtD(D04, D08), GeD(D04, D08), EqD(D04, D08), NeD(D04, D08), MinD(D04, D08), MaxD(D04, D08));
  PairD(140900, D04, D09, AddD(D04, D09), SubD(D04, D09), MulD(D04, D09), DivD(D04, D09), LtD(D04, D09), LeD(D04, D09), GtD(D04, D09), GeD(D04, D09), EqD(D04, D09), NeD(D04, D09), MinD(D04, D09), MaxD(D04, D09));
  PairD(141000, D04, D10, AddD(D04, D10), SubD(D04, D10), MulD(D04, D10), DivD(D04, D10), LtD(D04, D10), LeD(D04, D10), GtD(D04, D10), GeD(D04, D10), EqD(D04, D10), NeD(D04, D10), MinD(D04, D10), MaxD(D04, D10));
  PairD(141100, D04, D11, AddD(D04, D11), SubD(D04, D11), MulD(D04, D11), DivD(D04, D11), LtD(D04, D11), LeD(D04, D11), GtD(D04, D11), GeD(D04, D11), EqD(D04, D11), NeD(D04, D11), MinD(D04, D11), MaxD(D04, D11));
  PairD(141200, D04, D12, AddD(D04, D12), SubD(D04, D12), MulD(D04, D12), DivD(D04, D12), LtD(D04, D12), LeD(D04, D12), GtD(D04, D12), GeD(D04, D12), EqD(D04, D12), NeD(D04, D12), MinD(D04, D12), MaxD(D04, D12));
  PairD(141300, D04, D13, AddD(D04, D13), SubD(D04, D13), MulD(D04, D13), DivD(D04, D13), LtD(D04, D13), LeD(D04, D13), GtD(D04, D13), GeD(D04, D13), EqD(D04, D13), NeD(D04, D13), MinD(D04, D13), MaxD(D04, D13));
  PairD(141400, D04, D14, AddD(D04, D14), SubD(D04, D14), MulD(D04, D14), DivD(D04, D14), LtD(D04, D14), LeD(D04, D14), GtD(D04, D14), GeD(D04, D14), EqD(D04, D14), NeD(D04, D14), MinD(D04, D14), MaxD(D04, D14));
  PairD(141500, D04, D15, AddD(D04, D15), SubD(D04, D15), MulD(D04, D15), DivD(D04, D15), LtD(D04, D15), LeD(D04, D15), GtD(D04, D15), GeD(D04, D15), EqD(D04, D15), NeD(D04, D15), MinD(D04, D15), MaxD(D04, D15));
  PairD(150000, D05, D00, AddD(D05, D00), SubD(D05, D00), MulD(D05, D00), DivD(D05, D00), LtD(D05, D00), LeD(D05, D00), GtD(D05, D00), GeD(D05, D00), EqD(D05, D00), NeD(D05, D00), MinD(D05, D00), MaxD(D05, D00));
  PairD(150100, D05, D01, AddD(D05, D01), SubD(D05, D01), MulD(D05, D01), DivD(D05, D01), LtD(D05, D01), LeD(D05, D01), GtD(D05, D01), GeD(D05, D01), EqD(D05, D01), NeD(D05, D01), MinD(D05, D01), MaxD(D05, D01));
  PairD(150200, D05, D02, AddD(D05, D02), SubD(D05, D02), MulD(D05, D02), DivD(D05, D02), LtD(D05, D02), LeD(D05, D02), GtD(D05, D02), GeD(D05, D02), EqD(D05, D02), NeD(D05, D02), MinD(D05, D02), MaxD(D05, D02));
  PairD(150300, D05, D03, AddD(D05, D03), SubD(D05, D03), MulD(D05, D03), DivD(D05, D03), LtD(D05, D03), LeD(D05, D03), GtD(D05, D03), GeD(D05, D03), EqD(D05, D03), NeD(D05, D03), MinD(D05, D03), MaxD(D05, D03));
  PairD(150400, D05, D04, AddD(D05, D04), SubD(D05, D04), MulD(D05, D04), DivD(D05, D04), LtD(D05, D04), LeD(D05, D04), GtD(D05, D04), GeD(D05, D04), EqD(D05, D04), NeD(D05, D04), MinD(D05, D04), MaxD(D05, D04));
  PairD(150500, D05, D05, AddD(D05, D05), SubD(D05, D05), MulD(D05, D05), DivD(D05, D05), LtD(D05, D05), LeD(D05, D05), GtD(D05, D05), GeD(D05, D05), EqD(D05, D05), NeD(D05, D05), MinD(D05, D05), MaxD(D05, D05));
  PairD(150600, D05, D06, AddD(D05, D06), SubD(D05, D06), MulD(D05, D06), DivD(D05, D06), LtD(D05, D06), LeD(D05, D06), GtD(D05, D06), GeD(D05, D06), EqD(D05, D06), NeD(D05, D06), MinD(D05, D06), MaxD(D05, D06));
  PairD(150700, D05, D07, AddD(D05, D07), SubD(D05, D07), MulD(D05, D07), DivD(D05, D07), LtD(D05, D07), LeD(D05, D07), GtD(D05, D07), GeD(D05, D07), EqD(D05, D07), NeD(D05, D07), MinD(D05, D07), MaxD(D05, D07));
  PairD(150800, D05, D08, AddD(D05, D08), SubD(D05, D08), MulD(D05, D08), DivD(D05, D08), LtD(D05, D08), LeD(D05, D08), GtD(D05, D08), GeD(D05, D08), EqD(D05, D08), NeD(D05, D08), MinD(D05, D08), MaxD(D05, D08));
  PairD(150900, D05, D09, AddD(D05, D09), SubD(D05, D09), MulD(D05, D09), DivD(D05, D09), LtD(D05, D09), LeD(D05, D09), GtD(D05, D09), GeD(D05, D09), EqD(D05, D09), NeD(D05, D09), MinD(D05, D09), MaxD(D05, D09));
  PairD(151000, D05, D10, AddD(D05, D10), SubD(D05, D10), MulD(D05, D10), DivD(D05, D10), LtD(D05, D10), LeD(D05, D10), GtD(D05, D10), GeD(D05, D10), EqD(D05, D10), NeD(D05, D10), MinD(D05, D10), MaxD(D05, D10));
  PairD(151100, D05, D11, AddD(D05, D11), SubD(D05, D11), MulD(D05, D11), DivD(D05, D11), LtD(D05, D11), LeD(D05, D11), GtD(D05, D11), GeD(D05, D11), EqD(D05, D11), NeD(D05, D11), MinD(D05, D11), MaxD(D05, D11));
  PairD(151200, D05, D12, AddD(D05, D12), SubD(D05, D12), MulD(D05, D12), DivD(D05, D12), LtD(D05, D12), LeD(D05, D12), GtD(D05, D12), GeD(D05, D12), EqD(D05, D12), NeD(D05, D12), MinD(D05, D12), MaxD(D05, D12));
  PairD(151300, D05, D13, AddD(D05, D13), SubD(D05, D13), MulD(D05, D13), DivD(D05, D13), LtD(D05, D13), LeD(D05, D13), GtD(D05, D13), GeD(D05, D13), EqD(D05, D13), NeD(D05, D13), MinD(D05, D13), MaxD(D05, D13));
  PairD(151400, D05, D14, AddD(D05, D14), SubD(D05, D14), MulD(D05, D14), DivD(D05, D14), LtD(D05, D14), LeD(D05, D14), GtD(D05, D14), GeD(D05, D14), EqD(D05, D14), NeD(D05, D14), MinD(D05, D14), MaxD(D05, D14));
  PairD(151500, D05, D15, AddD(D05, D15), SubD(D05, D15), MulD(D05, D15), DivD(D05, D15), LtD(D05, D15), LeD(D05, D15), GtD(D05, D15), GeD(D05, D15), EqD(D05, D15), NeD(D05, D15), MinD(D05, D15), MaxD(D05, D15));
  PairD(160000, D06, D00, AddD(D06, D00), SubD(D06, D00), MulD(D06, D00), DivD(D06, D00), LtD(D06, D00), LeD(D06, D00), GtD(D06, D00), GeD(D06, D00), EqD(D06, D00), NeD(D06, D00), MinD(D06, D00), MaxD(D06, D00));
  PairD(160100, D06, D01, AddD(D06, D01), SubD(D06, D01), MulD(D06, D01), DivD(D06, D01), LtD(D06, D01), LeD(D06, D01), GtD(D06, D01), GeD(D06, D01), EqD(D06, D01), NeD(D06, D01), MinD(D06, D01), MaxD(D06, D01));
  PairD(160200, D06, D02, AddD(D06, D02), SubD(D06, D02), MulD(D06, D02), DivD(D06, D02), LtD(D06, D02), LeD(D06, D02), GtD(D06, D02), GeD(D06, D02), EqD(D06, D02), NeD(D06, D02), MinD(D06, D02), MaxD(D06, D02));
  PairD(160300, D06, D03, AddD(D06, D03), SubD(D06, D03), MulD(D06, D03), DivD(D06, D03), LtD(D06, D03), LeD(D06, D03), GtD(D06, D03), GeD(D06, D03), EqD(D06, D03), NeD(D06, D03), MinD(D06, D03), MaxD(D06, D03));
  PairD(160400, D06, D04, AddD(D06, D04), SubD(D06, D04), MulD(D06, D04), DivD(D06, D04), LtD(D06, D04), LeD(D06, D04), GtD(D06, D04), GeD(D06, D04), EqD(D06, D04), NeD(D06, D04), MinD(D06, D04), MaxD(D06, D04));
  PairD(160500, D06, D05, AddD(D06, D05), SubD(D06, D05), MulD(D06, D05), DivD(D06, D05), LtD(D06, D05), LeD(D06, D05), GtD(D06, D05), GeD(D06, D05), EqD(D06, D05), NeD(D06, D05), MinD(D06, D05), MaxD(D06, D05));
  PairD(160600, D06, D06, AddD(D06, D06), SubD(D06, D06), MulD(D06, D06), DivD(D06, D06), LtD(D06, D06), LeD(D06, D06), GtD(D06, D06), GeD(D06, D06), EqD(D06, D06), NeD(D06, D06), MinD(D06, D06), MaxD(D06, D06));
  PairD(160700, D06, D07, AddD(D06, D07), SubD(D06, D07), MulD(D06, D07), DivD(D06, D07), LtD(D06, D07), LeD(D06, D07), GtD(D06, D07), GeD(D06, D07), EqD(D06, D07), NeD(D06, D07), MinD(D06, D07), MaxD(D06, D07));
  PairD(160800, D06, D08, AddD(D06, D08), SubD(D06, D08), MulD(D06, D08), DivD(D06, D08), LtD(D06, D08), LeD(D06, D08), GtD(D06, D08), GeD(D06, D08), EqD(D06, D08), NeD(D06, D08), MinD(D06, D08), MaxD(D06, D08));
  PairD(160900, D06, D09, AddD(D06, D09), SubD(D06, D09), MulD(D06, D09), DivD(D06, D09), LtD(D06, D09), LeD(D06, D09), GtD(D06, D09), GeD(D06, D09), EqD(D06, D09), NeD(D06, D09), MinD(D06, D09), MaxD(D06, D09));
  PairD(161000, D06, D10, AddD(D06, D10), SubD(D06, D10), MulD(D06, D10), DivD(D06, D10), LtD(D06, D10), LeD(D06, D10), GtD(D06, D10), GeD(D06, D10), EqD(D06, D10), NeD(D06, D10), MinD(D06, D10), MaxD(D06, D10));
  PairD(161100, D06, D11, AddD(D06, D11), SubD(D06, D11), MulD(D06, D11), DivD(D06, D11), LtD(D06, D11), LeD(D06, D11), GtD(D06, D11), GeD(D06, D11), EqD(D06, D11), NeD(D06, D11), MinD(D06, D11), MaxD(D06, D11));
  PairD(161200, D06, D12, AddD(D06, D12), SubD(D06, D12), MulD(D06, D12), DivD(D06, D12), LtD(D06, D12), LeD(D06, D12), GtD(D06, D12), GeD(D06, D12), EqD(D06, D12), NeD(D06, D12), MinD(D06, D12), MaxD(D06, D12));
  PairD(161300, D06, D13, AddD(D06, D13), SubD(D06, D13), MulD(D06, D13), DivD(D06, D13), LtD(D06, D13), LeD(D06, D13), GtD(D06, D13), GeD(D06, D13), EqD(D06, D13), NeD(D06, D13), MinD(D06, D13), MaxD(D06, D13));
  PairD(161400, D06, D14, AddD(D06, D14), SubD(D06, D14), MulD(D06, D14), DivD(D06, D14), LtD(D06, D14), LeD(D06, D14), GtD(D06, D14), GeD(D06, D14), EqD(D06, D14), NeD(D06, D14), MinD(D06, D14), MaxD(D06, D14));
  PairD(161500, D06, D15, AddD(D06, D15), SubD(D06, D15), MulD(D06, D15), DivD(D06, D15), LtD(D06, D15), LeD(D06, D15), GtD(D06, D15), GeD(D06, D15), EqD(D06, D15), NeD(D06, D15), MinD(D06, D15), MaxD(D06, D15));
  PairD(170000, D07, D00, AddD(D07, D00), SubD(D07, D00), MulD(D07, D00), DivD(D07, D00), LtD(D07, D00), LeD(D07, D00), GtD(D07, D00), GeD(D07, D00), EqD(D07, D00), NeD(D07, D00), MinD(D07, D00), MaxD(D07, D00));
  PairD(170100, D07, D01, AddD(D07, D01), SubD(D07, D01), MulD(D07, D01), DivD(D07, D01), LtD(D07, D01), LeD(D07, D01), GtD(D07, D01), GeD(D07, D01), EqD(D07, D01), NeD(D07, D01), MinD(D07, D01), MaxD(D07, D01));
  PairD(170200, D07, D02, AddD(D07, D02), SubD(D07, D02), MulD(D07, D02), DivD(D07, D02), LtD(D07, D02), LeD(D07, D02), GtD(D07, D02), GeD(D07, D02), EqD(D07, D02), NeD(D07, D02), MinD(D07, D02), MaxD(D07, D02));
  PairD(170300, D07, D03, AddD(D07, D03), SubD(D07, D03), MulD(D07, D03), DivD(D07, D03), LtD(D07, D03), LeD(D07, D03), GtD(D07, D03), GeD(D07, D03), EqD(D07, D03), NeD(D07, D03), MinD(D07, D03), MaxD(D07, D03));
  PairD(170400, D07, D04, AddD(D07, D04), SubD(D07, D04), MulD(D07, D04), DivD(D07, D04), LtD(D07, D04), LeD(D07, D04), GtD(D07, D04), GeD(D07, D04), EqD(D07, D04), NeD(D07, D04), MinD(D07, D04), MaxD(D07, D04));
  PairD(170500, D07, D05, AddD(D07, D05), SubD(D07, D05), MulD(D07, D05), DivD(D07, D05), LtD(D07, D05), LeD(D07, D05), GtD(D07, D05), GeD(D07, D05), EqD(D07, D05), NeD(D07, D05), MinD(D07, D05), MaxD(D07, D05));
  PairD(170600, D07, D06, AddD(D07, D06), SubD(D07, D06), MulD(D07, D06), DivD(D07, D06), LtD(D07, D06), LeD(D07, D06), GtD(D07, D06), GeD(D07, D06), EqD(D07, D06), NeD(D07, D06), MinD(D07, D06), MaxD(D07, D06));
  PairD(170700, D07, D07, AddD(D07, D07), SubD(D07, D07), MulD(D07, D07), DivD(D07, D07), LtD(D07, D07), LeD(D07, D07), GtD(D07, D07), GeD(D07, D07), EqD(D07, D07), NeD(D07, D07), MinD(D07, D07), MaxD(D07, D07));
  PairD(170800, D07, D08, AddD(D07, D08), SubD(D07, D08), MulD(D07, D08), DivD(D07, D08), LtD(D07, D08), LeD(D07, D08), GtD(D07, D08), GeD(D07, D08), EqD(D07, D08), NeD(D07, D08), MinD(D07, D08), MaxD(D07, D08));
  PairD(170900, D07, D09, AddD(D07, D09), SubD(D07, D09), MulD(D07, D09), DivD(D07, D09), LtD(D07, D09), LeD(D07, D09), GtD(D07, D09), GeD(D07, D09), EqD(D07, D09), NeD(D07, D09), MinD(D07, D09), MaxD(D07, D09));
  PairD(171000, D07, D10, AddD(D07, D10), SubD(D07, D10), MulD(D07, D10), DivD(D07, D10), LtD(D07, D10), LeD(D07, D10), GtD(D07, D10), GeD(D07, D10), EqD(D07, D10), NeD(D07, D10), MinD(D07, D10), MaxD(D07, D10));
  PairD(171100, D07, D11, AddD(D07, D11), SubD(D07, D11), MulD(D07, D11), DivD(D07, D11), LtD(D07, D11), LeD(D07, D11), GtD(D07, D11), GeD(D07, D11), EqD(D07, D11), NeD(D07, D11), MinD(D07, D11), MaxD(D07, D11));
  PairD(171200, D07, D12, AddD(D07, D12), SubD(D07, D12), MulD(D07, D12), DivD(D07, D12), LtD(D07, D12), LeD(D07, D12), GtD(D07, D12), GeD(D07, D12), EqD(D07, D12), NeD(D07, D12), MinD(D07, D12), MaxD(D07, D12));
  PairD(171300, D07, D13, AddD(D07, D13), SubD(D07, D13), MulD(D07, D13), DivD(D07, D13), LtD(D07, D13), LeD(D07, D13), GtD(D07, D13), GeD(D07, D13), EqD(D07, D13), NeD(D07, D13), MinD(D07, D13), MaxD(D07, D13));
  PairD(171400, D07, D14, AddD(D07, D14), SubD(D07, D14), MulD(D07, D14), DivD(D07, D14), LtD(D07, D14), LeD(D07, D14), GtD(D07, D14), GeD(D07, D14), EqD(D07, D14), NeD(D07, D14), MinD(D07, D14), MaxD(D07, D14));
  PairD(171500, D07, D15, AddD(D07, D15), SubD(D07, D15), MulD(D07, D15), DivD(D07, D15), LtD(D07, D15), LeD(D07, D15), GtD(D07, D15), GeD(D07, D15), EqD(D07, D15), NeD(D07, D15), MinD(D07, D15), MaxD(D07, D15));
  PairD(180000, D08, D00, AddD(D08, D00), SubD(D08, D00), MulD(D08, D00), DivD(D08, D00), LtD(D08, D00), LeD(D08, D00), GtD(D08, D00), GeD(D08, D00), EqD(D08, D00), NeD(D08, D00), MinD(D08, D00), MaxD(D08, D00));
  PairD(180100, D08, D01, AddD(D08, D01), SubD(D08, D01), MulD(D08, D01), DivD(D08, D01), LtD(D08, D01), LeD(D08, D01), GtD(D08, D01), GeD(D08, D01), EqD(D08, D01), NeD(D08, D01), MinD(D08, D01), MaxD(D08, D01));
  PairD(180200, D08, D02, AddD(D08, D02), SubD(D08, D02), MulD(D08, D02), DivD(D08, D02), LtD(D08, D02), LeD(D08, D02), GtD(D08, D02), GeD(D08, D02), EqD(D08, D02), NeD(D08, D02), MinD(D08, D02), MaxD(D08, D02));
  PairD(180300, D08, D03, AddD(D08, D03), SubD(D08, D03), MulD(D08, D03), DivD(D08, D03), LtD(D08, D03), LeD(D08, D03), GtD(D08, D03), GeD(D08, D03), EqD(D08, D03), NeD(D08, D03), MinD(D08, D03), MaxD(D08, D03));
  PairD(180400, D08, D04, AddD(D08, D04), SubD(D08, D04), MulD(D08, D04), DivD(D08, D04), LtD(D08, D04), LeD(D08, D04), GtD(D08, D04), GeD(D08, D04), EqD(D08, D04), NeD(D08, D04), MinD(D08, D04), MaxD(D08, D04));
  PairD(180500, D08, D05, AddD(D08, D05), SubD(D08, D05), MulD(D08, D05), DivD(D08, D05), LtD(D08, D05), LeD(D08, D05), GtD(D08, D05), GeD(D08, D05), EqD(D08, D05), NeD(D08, D05), MinD(D08, D05), MaxD(D08, D05));
  PairD(180600, D08, D06, AddD(D08, D06), SubD(D08, D06), MulD(D08, D06), DivD(D08, D06), LtD(D08, D06), LeD(D08, D06), GtD(D08, D06), GeD(D08, D06), EqD(D08, D06), NeD(D08, D06), MinD(D08, D06), MaxD(D08, D06));
  PairD(180700, D08, D07, AddD(D08, D07), SubD(D08, D07), MulD(D08, D07), DivD(D08, D07), LtD(D08, D07), LeD(D08, D07), GtD(D08, D07), GeD(D08, D07), EqD(D08, D07), NeD(D08, D07), MinD(D08, D07), MaxD(D08, D07));
  PairD(180800, D08, D08, AddD(D08, D08), SubD(D08, D08), MulD(D08, D08), DivD(D08, D08), LtD(D08, D08), LeD(D08, D08), GtD(D08, D08), GeD(D08, D08), EqD(D08, D08), NeD(D08, D08), MinD(D08, D08), MaxD(D08, D08));
  PairD(180900, D08, D09, AddD(D08, D09), SubD(D08, D09), MulD(D08, D09), DivD(D08, D09), LtD(D08, D09), LeD(D08, D09), GtD(D08, D09), GeD(D08, D09), EqD(D08, D09), NeD(D08, D09), MinD(D08, D09), MaxD(D08, D09));
  PairD(181000, D08, D10, AddD(D08, D10), SubD(D08, D10), MulD(D08, D10), DivD(D08, D10), LtD(D08, D10), LeD(D08, D10), GtD(D08, D10), GeD(D08, D10), EqD(D08, D10), NeD(D08, D10), MinD(D08, D10), MaxD(D08, D10));
  PairD(181100, D08, D11, AddD(D08, D11), SubD(D08, D11), MulD(D08, D11), DivD(D08, D11), LtD(D08, D11), LeD(D08, D11), GtD(D08, D11), GeD(D08, D11), EqD(D08, D11), NeD(D08, D11), MinD(D08, D11), MaxD(D08, D11));
  PairD(181200, D08, D12, AddD(D08, D12), SubD(D08, D12), MulD(D08, D12), DivD(D08, D12), LtD(D08, D12), LeD(D08, D12), GtD(D08, D12), GeD(D08, D12), EqD(D08, D12), NeD(D08, D12), MinD(D08, D12), MaxD(D08, D12));
  PairD(181300, D08, D13, AddD(D08, D13), SubD(D08, D13), MulD(D08, D13), DivD(D08, D13), LtD(D08, D13), LeD(D08, D13), GtD(D08, D13), GeD(D08, D13), EqD(D08, D13), NeD(D08, D13), MinD(D08, D13), MaxD(D08, D13));
  PairD(181400, D08, D14, AddD(D08, D14), SubD(D08, D14), MulD(D08, D14), DivD(D08, D14), LtD(D08, D14), LeD(D08, D14), GtD(D08, D14), GeD(D08, D14), EqD(D08, D14), NeD(D08, D14), MinD(D08, D14), MaxD(D08, D14));
  PairD(181500, D08, D15, AddD(D08, D15), SubD(D08, D15), MulD(D08, D15), DivD(D08, D15), LtD(D08, D15), LeD(D08, D15), GtD(D08, D15), GeD(D08, D15), EqD(D08, D15), NeD(D08, D15), MinD(D08, D15), MaxD(D08, D15));
  PairD(190000, D09, D00, AddD(D09, D00), SubD(D09, D00), MulD(D09, D00), DivD(D09, D00), LtD(D09, D00), LeD(D09, D00), GtD(D09, D00), GeD(D09, D00), EqD(D09, D00), NeD(D09, D00), MinD(D09, D00), MaxD(D09, D00));
  PairD(190100, D09, D01, AddD(D09, D01), SubD(D09, D01), MulD(D09, D01), DivD(D09, D01), LtD(D09, D01), LeD(D09, D01), GtD(D09, D01), GeD(D09, D01), EqD(D09, D01), NeD(D09, D01), MinD(D09, D01), MaxD(D09, D01));
  PairD(190200, D09, D02, AddD(D09, D02), SubD(D09, D02), MulD(D09, D02), DivD(D09, D02), LtD(D09, D02), LeD(D09, D02), GtD(D09, D02), GeD(D09, D02), EqD(D09, D02), NeD(D09, D02), MinD(D09, D02), MaxD(D09, D02));
  PairD(190300, D09, D03, AddD(D09, D03), SubD(D09, D03), MulD(D09, D03), DivD(D09, D03), LtD(D09, D03), LeD(D09, D03), GtD(D09, D03), GeD(D09, D03), EqD(D09, D03), NeD(D09, D03), MinD(D09, D03), MaxD(D09, D03));
  PairD(190400, D09, D04, AddD(D09, D04), SubD(D09, D04), MulD(D09, D04), DivD(D09, D04), LtD(D09, D04), LeD(D09, D04), GtD(D09, D04), GeD(D09, D04), EqD(D09, D04), NeD(D09, D04), MinD(D09, D04), MaxD(D09, D04));
  PairD(190500, D09, D05, AddD(D09, D05), SubD(D09, D05), MulD(D09, D05), DivD(D09, D05), LtD(D09, D05), LeD(D09, D05), GtD(D09, D05), GeD(D09, D05), EqD(D09, D05), NeD(D09, D05), MinD(D09, D05), MaxD(D09, D05));
  PairD(190600, D09, D06, AddD(D09, D06), SubD(D09, D06), MulD(D09, D06), DivD(D09, D06), LtD(D09, D06), LeD(D09, D06), GtD(D09, D06), GeD(D09, D06), EqD(D09, D06), NeD(D09, D06), MinD(D09, D06), MaxD(D09, D06));
  PairD(190700, D09, D07, AddD(D09, D07), SubD(D09, D07), MulD(D09, D07), DivD(D09, D07), LtD(D09, D07), LeD(D09, D07), GtD(D09, D07), GeD(D09, D07), EqD(D09, D07), NeD(D09, D07), MinD(D09, D07), MaxD(D09, D07));
  PairD(190800, D09, D08, AddD(D09, D08), SubD(D09, D08), MulD(D09, D08), DivD(D09, D08), LtD(D09, D08), LeD(D09, D08), GtD(D09, D08), GeD(D09, D08), EqD(D09, D08), NeD(D09, D08), MinD(D09, D08), MaxD(D09, D08));
  PairD(190900, D09, D09, AddD(D09, D09), SubD(D09, D09), MulD(D09, D09), DivD(D09, D09), LtD(D09, D09), LeD(D09, D09), GtD(D09, D09), GeD(D09, D09), EqD(D09, D09), NeD(D09, D09), MinD(D09, D09), MaxD(D09, D09));
  PairD(191000, D09, D10, AddD(D09, D10), SubD(D09, D10), MulD(D09, D10), DivD(D09, D10), LtD(D09, D10), LeD(D09, D10), GtD(D09, D10), GeD(D09, D10), EqD(D09, D10), NeD(D09, D10), MinD(D09, D10), MaxD(D09, D10));
  PairD(191100, D09, D11, AddD(D09, D11), SubD(D09, D11), MulD(D09, D11), DivD(D09, D11), LtD(D09, D11), LeD(D09, D11), GtD(D09, D11), GeD(D09, D11), EqD(D09, D11), NeD(D09, D11), MinD(D09, D11), MaxD(D09, D11));
  PairD(191200, D09, D12, AddD(D09, D12), SubD(D09, D12), MulD(D09, D12), DivD(D09, D12), LtD(D09, D12), LeD(D09, D12), GtD(D09, D12), GeD(D09, D12), EqD(D09, D12), NeD(D09, D12), MinD(D09, D12), MaxD(D09, D12));
  PairD(191300, D09, D13, AddD(D09, D13), SubD(D09, D13), MulD(D09, D13), DivD(D09, D13), LtD(D09, D13), LeD(D09, D13), GtD(D09, D13), GeD(D09, D13), EqD(D09, D13), NeD(D09, D13), MinD(D09, D13), MaxD(D09, D13));
  PairD(191400, D09, D14, AddD(D09, D14), SubD(D09, D14), MulD(D09, D14), DivD(D09, D14), LtD(D09, D14), LeD(D09, D14), GtD(D09, D14), GeD(D09, D14), EqD(D09, D14), NeD(D09, D14), MinD(D09, D14), MaxD(D09, D14));
  PairD(191500, D09, D15, AddD(D09, D15), SubD(D09, D15), MulD(D09, D15), DivD(D09, D15), LtD(D09, D15), LeD(D09, D15), GtD(D09, D15), GeD(D09, D15), EqD(D09, D15), NeD(D09, D15), MinD(D09, D15), MaxD(D09, D15));
  PairD(200000, D10, D00, AddD(D10, D00), SubD(D10, D00), MulD(D10, D00), DivD(D10, D00), LtD(D10, D00), LeD(D10, D00), GtD(D10, D00), GeD(D10, D00), EqD(D10, D00), NeD(D10, D00), MinD(D10, D00), MaxD(D10, D00));
  PairD(200100, D10, D01, AddD(D10, D01), SubD(D10, D01), MulD(D10, D01), DivD(D10, D01), LtD(D10, D01), LeD(D10, D01), GtD(D10, D01), GeD(D10, D01), EqD(D10, D01), NeD(D10, D01), MinD(D10, D01), MaxD(D10, D01));
  PairD(200200, D10, D02, AddD(D10, D02), SubD(D10, D02), MulD(D10, D02), DivD(D10, D02), LtD(D10, D02), LeD(D10, D02), GtD(D10, D02), GeD(D10, D02), EqD(D10, D02), NeD(D10, D02), MinD(D10, D02), MaxD(D10, D02));
  PairD(200300, D10, D03, AddD(D10, D03), SubD(D10, D03), MulD(D10, D03), DivD(D10, D03), LtD(D10, D03), LeD(D10, D03), GtD(D10, D03), GeD(D10, D03), EqD(D10, D03), NeD(D10, D03), MinD(D10, D03), MaxD(D10, D03));
  PairD(200400, D10, D04, AddD(D10, D04), SubD(D10, D04), MulD(D10, D04), DivD(D10, D04), LtD(D10, D04), LeD(D10, D04), GtD(D10, D04), GeD(D10, D04), EqD(D10, D04), NeD(D10, D04), MinD(D10, D04), MaxD(D10, D04));
  PairD(200500, D10, D05, AddD(D10, D05), SubD(D10, D05), MulD(D10, D05), DivD(D10, D05), LtD(D10, D05), LeD(D10, D05), GtD(D10, D05), GeD(D10, D05), EqD(D10, D05), NeD(D10, D05), MinD(D10, D05), MaxD(D10, D05));
  PairD(200600, D10, D06, AddD(D10, D06), SubD(D10, D06), MulD(D10, D06), DivD(D10, D06), LtD(D10, D06), LeD(D10, D06), GtD(D10, D06), GeD(D10, D06), EqD(D10, D06), NeD(D10, D06), MinD(D10, D06), MaxD(D10, D06));
  PairD(200700, D10, D07, AddD(D10, D07), SubD(D10, D07), MulD(D10, D07), DivD(D10, D07), LtD(D10, D07), LeD(D10, D07), GtD(D10, D07), GeD(D10, D07), EqD(D10, D07), NeD(D10, D07), MinD(D10, D07), MaxD(D10, D07));
  PairD(200800, D10, D08, AddD(D10, D08), SubD(D10, D08), MulD(D10, D08), DivD(D10, D08), LtD(D10, D08), LeD(D10, D08), GtD(D10, D08), GeD(D10, D08), EqD(D10, D08), NeD(D10, D08), MinD(D10, D08), MaxD(D10, D08));
  PairD(200900, D10, D09, AddD(D10, D09), SubD(D10, D09), MulD(D10, D09), DivD(D10, D09), LtD(D10, D09), LeD(D10, D09), GtD(D10, D09), GeD(D10, D09), EqD(D10, D09), NeD(D10, D09), MinD(D10, D09), MaxD(D10, D09));
  PairD(201000, D10, D10, AddD(D10, D10), SubD(D10, D10), MulD(D10, D10), DivD(D10, D10), LtD(D10, D10), LeD(D10, D10), GtD(D10, D10), GeD(D10, D10), EqD(D10, D10), NeD(D10, D10), MinD(D10, D10), MaxD(D10, D10));
  PairD(201100, D10, D11, AddD(D10, D11), SubD(D10, D11), MulD(D10, D11), DivD(D10, D11), LtD(D10, D11), LeD(D10, D11), GtD(D10, D11), GeD(D10, D11), EqD(D10, D11), NeD(D10, D11), MinD(D10, D11), MaxD(D10, D11));
  PairD(201200, D10, D12, AddD(D10, D12), SubD(D10, D12), MulD(D10, D12), DivD(D10, D12), LtD(D10, D12), LeD(D10, D12), GtD(D10, D12), GeD(D10, D12), EqD(D10, D12), NeD(D10, D12), MinD(D10, D12), MaxD(D10, D12));
  PairD(201300, D10, D13, AddD(D10, D13), SubD(D10, D13), MulD(D10, D13), DivD(D10, D13), LtD(D10, D13), LeD(D10, D13), GtD(D10, D13), GeD(D10, D13), EqD(D10, D13), NeD(D10, D13), MinD(D10, D13), MaxD(D10, D13));
  PairD(201400, D10, D14, AddD(D10, D14), SubD(D10, D14), MulD(D10, D14), DivD(D10, D14), LtD(D10, D14), LeD(D10, D14), GtD(D10, D14), GeD(D10, D14), EqD(D10, D14), NeD(D10, D14), MinD(D10, D14), MaxD(D10, D14));
  PairD(201500, D10, D15, AddD(D10, D15), SubD(D10, D15), MulD(D10, D15), DivD(D10, D15), LtD(D10, D15), LeD(D10, D15), GtD(D10, D15), GeD(D10, D15), EqD(D10, D15), NeD(D10, D15), MinD(D10, D15), MaxD(D10, D15));
  PairD(210000, D11, D00, AddD(D11, D00), SubD(D11, D00), MulD(D11, D00), DivD(D11, D00), LtD(D11, D00), LeD(D11, D00), GtD(D11, D00), GeD(D11, D00), EqD(D11, D00), NeD(D11, D00), MinD(D11, D00), MaxD(D11, D00));
  PairD(210100, D11, D01, AddD(D11, D01), SubD(D11, D01), MulD(D11, D01), DivD(D11, D01), LtD(D11, D01), LeD(D11, D01), GtD(D11, D01), GeD(D11, D01), EqD(D11, D01), NeD(D11, D01), MinD(D11, D01), MaxD(D11, D01));
  PairD(210200, D11, D02, AddD(D11, D02), SubD(D11, D02), MulD(D11, D02), DivD(D11, D02), LtD(D11, D02), LeD(D11, D02), GtD(D11, D02), GeD(D11, D02), EqD(D11, D02), NeD(D11, D02), MinD(D11, D02), MaxD(D11, D02));
  PairD(210300, D11, D03, AddD(D11, D03), SubD(D11, D03), MulD(D11, D03), DivD(D11, D03), LtD(D11, D03), LeD(D11, D03), GtD(D11, D03), GeD(D11, D03), EqD(D11, D03), NeD(D11, D03), MinD(D11, D03), MaxD(D11, D03));
  PairD(210400, D11, D04, AddD(D11, D04), SubD(D11, D04), MulD(D11, D04), DivD(D11, D04), LtD(D11, D04), LeD(D11, D04), GtD(D11, D04), GeD(D11, D04), EqD(D11, D04), NeD(D11, D04), MinD(D11, D04), MaxD(D11, D04));
  PairD(210500, D11, D05, AddD(D11, D05), SubD(D11, D05), MulD(D11, D05), DivD(D11, D05), LtD(D11, D05), LeD(D11, D05), GtD(D11, D05), GeD(D11, D05), EqD(D11, D05), NeD(D11, D05), MinD(D11, D05), MaxD(D11, D05));
  PairD(210600, D11, D06, AddD(D11, D06), SubD(D11, D06), MulD(D11, D06), DivD(D11, D06), LtD(D11, D06), LeD(D11, D06), GtD(D11, D06), GeD(D11, D06), EqD(D11, D06), NeD(D11, D06), MinD(D11, D06), MaxD(D11, D06));
  PairD(210700, D11, D07, AddD(D11, D07), SubD(D11, D07), MulD(D11, D07), DivD(D11, D07), LtD(D11, D07), LeD(D11, D07), GtD(D11, D07), GeD(D11, D07), EqD(D11, D07), NeD(D11, D07), MinD(D11, D07), MaxD(D11, D07));
  PairD(210800, D11, D08, AddD(D11, D08), SubD(D11, D08), MulD(D11, D08), DivD(D11, D08), LtD(D11, D08), LeD(D11, D08), GtD(D11, D08), GeD(D11, D08), EqD(D11, D08), NeD(D11, D08), MinD(D11, D08), MaxD(D11, D08));
  PairD(210900, D11, D09, AddD(D11, D09), SubD(D11, D09), MulD(D11, D09), DivD(D11, D09), LtD(D11, D09), LeD(D11, D09), GtD(D11, D09), GeD(D11, D09), EqD(D11, D09), NeD(D11, D09), MinD(D11, D09), MaxD(D11, D09));
  PairD(211000, D11, D10, AddD(D11, D10), SubD(D11, D10), MulD(D11, D10), DivD(D11, D10), LtD(D11, D10), LeD(D11, D10), GtD(D11, D10), GeD(D11, D10), EqD(D11, D10), NeD(D11, D10), MinD(D11, D10), MaxD(D11, D10));
  PairD(211100, D11, D11, AddD(D11, D11), SubD(D11, D11), MulD(D11, D11), DivD(D11, D11), LtD(D11, D11), LeD(D11, D11), GtD(D11, D11), GeD(D11, D11), EqD(D11, D11), NeD(D11, D11), MinD(D11, D11), MaxD(D11, D11));
  PairD(211200, D11, D12, AddD(D11, D12), SubD(D11, D12), MulD(D11, D12), DivD(D11, D12), LtD(D11, D12), LeD(D11, D12), GtD(D11, D12), GeD(D11, D12), EqD(D11, D12), NeD(D11, D12), MinD(D11, D12), MaxD(D11, D12));
  PairD(211300, D11, D13, AddD(D11, D13), SubD(D11, D13), MulD(D11, D13), DivD(D11, D13), LtD(D11, D13), LeD(D11, D13), GtD(D11, D13), GeD(D11, D13), EqD(D11, D13), NeD(D11, D13), MinD(D11, D13), MaxD(D11, D13));
  PairD(211400, D11, D14, AddD(D11, D14), SubD(D11, D14), MulD(D11, D14), DivD(D11, D14), LtD(D11, D14), LeD(D11, D14), GtD(D11, D14), GeD(D11, D14), EqD(D11, D14), NeD(D11, D14), MinD(D11, D14), MaxD(D11, D14));
  PairD(211500, D11, D15, AddD(D11, D15), SubD(D11, D15), MulD(D11, D15), DivD(D11, D15), LtD(D11, D15), LeD(D11, D15), GtD(D11, D15), GeD(D11, D15), EqD(D11, D15), NeD(D11, D15), MinD(D11, D15), MaxD(D11, D15));
  PairD(220000, D12, D00, AddD(D12, D00), SubD(D12, D00), MulD(D12, D00), DivD(D12, D00), LtD(D12, D00), LeD(D12, D00), GtD(D12, D00), GeD(D12, D00), EqD(D12, D00), NeD(D12, D00), MinD(D12, D00), MaxD(D12, D00));
  PairD(220100, D12, D01, AddD(D12, D01), SubD(D12, D01), MulD(D12, D01), DivD(D12, D01), LtD(D12, D01), LeD(D12, D01), GtD(D12, D01), GeD(D12, D01), EqD(D12, D01), NeD(D12, D01), MinD(D12, D01), MaxD(D12, D01));
  PairD(220200, D12, D02, AddD(D12, D02), SubD(D12, D02), MulD(D12, D02), DivD(D12, D02), LtD(D12, D02), LeD(D12, D02), GtD(D12, D02), GeD(D12, D02), EqD(D12, D02), NeD(D12, D02), MinD(D12, D02), MaxD(D12, D02));
  PairD(220300, D12, D03, AddD(D12, D03), SubD(D12, D03), MulD(D12, D03), DivD(D12, D03), LtD(D12, D03), LeD(D12, D03), GtD(D12, D03), GeD(D12, D03), EqD(D12, D03), NeD(D12, D03), MinD(D12, D03), MaxD(D12, D03));
  PairD(220400, D12, D04, AddD(D12, D04), SubD(D12, D04), MulD(D12, D04), DivD(D12, D04), LtD(D12, D04), LeD(D12, D04), GtD(D12, D04), GeD(D12, D04), EqD(D12, D04), NeD(D12, D04), MinD(D12, D04), MaxD(D12, D04));
  PairD(220500, D12, D05, AddD(D12, D05), SubD(D12, D05), MulD(D12, D05), DivD(D12, D05), LtD(D12, D05), LeD(D12, D05), GtD(D12, D05), GeD(D12, D05), EqD(D12, D05), NeD(D12, D05), MinD(D12, D05), MaxD(D12, D05));
  PairD(220600, D12, D06, AddD(D12, D06), SubD(D12, D06), MulD(D12, D06), DivD(D12, D06), LtD(D12, D06), LeD(D12, D06), GtD(D12, D06), GeD(D12, D06), EqD(D12, D06), NeD(D12, D06), MinD(D12, D06), MaxD(D12, D06));
  PairD(220700, D12, D07, AddD(D12, D07), SubD(D12, D07), MulD(D12, D07), DivD(D12, D07), LtD(D12, D07), LeD(D12, D07), GtD(D12, D07), GeD(D12, D07), EqD(D12, D07), NeD(D12, D07), MinD(D12, D07), MaxD(D12, D07));
  PairD(220800, D12, D08, AddD(D12, D08), SubD(D12, D08), MulD(D12, D08), DivD(D12, D08), LtD(D12, D08), LeD(D12, D08), GtD(D12, D08), GeD(D12, D08), EqD(D12, D08), NeD(D12, D08), MinD(D12, D08), MaxD(D12, D08));
  PairD(220900, D12, D09, AddD(D12, D09), SubD(D12, D09), MulD(D12, D09), DivD(D12, D09), LtD(D12, D09), LeD(D12, D09), GtD(D12, D09), GeD(D12, D09), EqD(D12, D09), NeD(D12, D09), MinD(D12, D09), MaxD(D12, D09));
  PairD(221000, D12, D10, AddD(D12, D10), SubD(D12, D10), MulD(D12, D10), DivD(D12, D10), LtD(D12, D10), LeD(D12, D10), GtD(D12, D10), GeD(D12, D10), EqD(D12, D10), NeD(D12, D10), MinD(D12, D10), MaxD(D12, D10));
  PairD(221100, D12, D11, AddD(D12, D11), SubD(D12, D11), MulD(D12, D11), DivD(D12, D11), LtD(D12, D11), LeD(D12, D11), GtD(D12, D11), GeD(D12, D11), EqD(D12, D11), NeD(D12, D11), MinD(D12, D11), MaxD(D12, D11));
  PairD(221200, D12, D12, AddD(D12, D12), SubD(D12, D12), MulD(D12, D12), DivD(D12, D12), LtD(D12, D12), LeD(D12, D12), GtD(D12, D12), GeD(D12, D12), EqD(D12, D12), NeD(D12, D12), MinD(D12, D12), MaxD(D12, D12));
  PairD(221300, D12, D13, AddD(D12, D13), SubD(D12, D13), MulD(D12, D13), DivD(D12, D13), LtD(D12, D13), LeD(D12, D13), GtD(D12, D13), GeD(D12, D13), EqD(D12, D13), NeD(D12, D13), MinD(D12, D13), MaxD(D12, D13));
  PairD(221400, D12, D14, AddD(D12, D14), SubD(D12, D14), MulD(D12, D14), DivD(D12, D14), LtD(D12, D14), LeD(D12, D14), GtD(D12, D14), GeD(D12, D14), EqD(D12, D14), NeD(D12, D14), MinD(D12, D14), MaxD(D12, D14));
  PairD(221500, D12, D15, AddD(D12, D15), SubD(D12, D15), MulD(D12, D15), DivD(D12, D15), LtD(D12, D15), LeD(D12, D15), GtD(D12, D15), GeD(D12, D15), EqD(D12, D15), NeD(D12, D15), MinD(D12, D15), MaxD(D12, D15));
  PairD(230000, D13, D00, AddD(D13, D00), SubD(D13, D00), MulD(D13, D00), DivD(D13, D00), LtD(D13, D00), LeD(D13, D00), GtD(D13, D00), GeD(D13, D00), EqD(D13, D00), NeD(D13, D00), MinD(D13, D00), MaxD(D13, D00));
  PairD(230100, D13, D01, AddD(D13, D01), SubD(D13, D01), MulD(D13, D01), DivD(D13, D01), LtD(D13, D01), LeD(D13, D01), GtD(D13, D01), GeD(D13, D01), EqD(D13, D01), NeD(D13, D01), MinD(D13, D01), MaxD(D13, D01));
  PairD(230200, D13, D02, AddD(D13, D02), SubD(D13, D02), MulD(D13, D02), DivD(D13, D02), LtD(D13, D02), LeD(D13, D02), GtD(D13, D02), GeD(D13, D02), EqD(D13, D02), NeD(D13, D02), MinD(D13, D02), MaxD(D13, D02));
  PairD(230300, D13, D03, AddD(D13, D03), SubD(D13, D03), MulD(D13, D03), DivD(D13, D03), LtD(D13, D03), LeD(D13, D03), GtD(D13, D03), GeD(D13, D03), EqD(D13, D03), NeD(D13, D03), MinD(D13, D03), MaxD(D13, D03));
  PairD(230400, D13, D04, AddD(D13, D04), SubD(D13, D04), MulD(D13, D04), DivD(D13, D04), LtD(D13, D04), LeD(D13, D04), GtD(D13, D04), GeD(D13, D04), EqD(D13, D04), NeD(D13, D04), MinD(D13, D04), MaxD(D13, D04));
  PairD(230500, D13, D05, AddD(D13, D05), SubD(D13, D05), MulD(D13, D05), DivD(D13, D05), LtD(D13, D05), LeD(D13, D05), GtD(D13, D05), GeD(D13, D05), EqD(D13, D05), NeD(D13, D05), MinD(D13, D05), MaxD(D13, D05));
  PairD(230600, D13, D06, AddD(D13, D06), SubD(D13, D06), MulD(D13, D06), DivD(D13, D06), LtD(D13, D06), LeD(D13, D06), GtD(D13, D06), GeD(D13, D06), EqD(D13, D06), NeD(D13, D06), MinD(D13, D06), MaxD(D13, D06));
  PairD(230700, D13, D07, AddD(D13, D07), SubD(D13, D07), MulD(D13, D07), DivD(D13, D07), LtD(D13, D07), LeD(D13, D07), GtD(D13, D07), GeD(D13, D07), EqD(D13, D07), NeD(D13, D07), MinD(D13, D07), MaxD(D13, D07));
  PairD(230800, D13, D08, AddD(D13, D08), SubD(D13, D08), MulD(D13, D08), DivD(D13, D08), LtD(D13, D08), LeD(D13, D08), GtD(D13, D08), GeD(D13, D08), EqD(D13, D08), NeD(D13, D08), MinD(D13, D08), MaxD(D13, D08));
  PairD(230900, D13, D09, AddD(D13, D09), SubD(D13, D09), MulD(D13, D09), DivD(D13, D09), LtD(D13, D09), LeD(D13, D09), GtD(D13, D09), GeD(D13, D09), EqD(D13, D09), NeD(D13, D09), MinD(D13, D09), MaxD(D13, D09));
  PairD(231000, D13, D10, AddD(D13, D10), SubD(D13, D10), MulD(D13, D10), DivD(D13, D10), LtD(D13, D10), LeD(D13, D10), GtD(D13, D10), GeD(D13, D10), EqD(D13, D10), NeD(D13, D10), MinD(D13, D10), MaxD(D13, D10));
  PairD(231100, D13, D11, AddD(D13, D11), SubD(D13, D11), MulD(D13, D11), DivD(D13, D11), LtD(D13, D11), LeD(D13, D11), GtD(D13, D11), GeD(D13, D11), EqD(D13, D11), NeD(D13, D11), MinD(D13, D11), MaxD(D13, D11));
  PairD(231200, D13, D12, AddD(D13, D12), SubD(D13, D12), MulD(D13, D12), DivD(D13, D12), LtD(D13, D12), LeD(D13, D12), GtD(D13, D12), GeD(D13, D12), EqD(D13, D12), NeD(D13, D12), MinD(D13, D12), MaxD(D13, D12));
  PairD(231300, D13, D13, AddD(D13, D13), SubD(D13, D13), MulD(D13, D13), DivD(D13, D13), LtD(D13, D13), LeD(D13, D13), GtD(D13, D13), GeD(D13, D13), EqD(D13, D13), NeD(D13, D13), MinD(D13, D13), MaxD(D13, D13));
  PairD(231400, D13, D14, AddD(D13, D14), SubD(D13, D14), MulD(D13, D14), DivD(D13, D14), LtD(D13, D14), LeD(D13, D14), GtD(D13, D14), GeD(D13, D14), EqD(D13, D14), NeD(D13, D14), MinD(D13, D14), MaxD(D13, D14));
  PairD(231500, D13, D15, AddD(D13, D15), SubD(D13, D15), MulD(D13, D15), DivD(D13, D15), LtD(D13, D15), LeD(D13, D15), GtD(D13, D15), GeD(D13, D15), EqD(D13, D15), NeD(D13, D15), MinD(D13, D15), MaxD(D13, D15));
  PairD(240000, D14, D00, AddD(D14, D00), SubD(D14, D00), MulD(D14, D00), DivD(D14, D00), LtD(D14, D00), LeD(D14, D00), GtD(D14, D00), GeD(D14, D00), EqD(D14, D00), NeD(D14, D00), MinD(D14, D00), MaxD(D14, D00));
  PairD(240100, D14, D01, AddD(D14, D01), SubD(D14, D01), MulD(D14, D01), DivD(D14, D01), LtD(D14, D01), LeD(D14, D01), GtD(D14, D01), GeD(D14, D01), EqD(D14, D01), NeD(D14, D01), MinD(D14, D01), MaxD(D14, D01));
  PairD(240200, D14, D02, AddD(D14, D02), SubD(D14, D02), MulD(D14, D02), DivD(D14, D02), LtD(D14, D02), LeD(D14, D02), GtD(D14, D02), GeD(D14, D02), EqD(D14, D02), NeD(D14, D02), MinD(D14, D02), MaxD(D14, D02));
  PairD(240300, D14, D03, AddD(D14, D03), SubD(D14, D03), MulD(D14, D03), DivD(D14, D03), LtD(D14, D03), LeD(D14, D03), GtD(D14, D03), GeD(D14, D03), EqD(D14, D03), NeD(D14, D03), MinD(D14, D03), MaxD(D14, D03));
  PairD(240400, D14, D04, AddD(D14, D04), SubD(D14, D04), MulD(D14, D04), DivD(D14, D04), LtD(D14, D04), LeD(D14, D04), GtD(D14, D04), GeD(D14, D04), EqD(D14, D04), NeD(D14, D04), MinD(D14, D04), MaxD(D14, D04));
  PairD(240500, D14, D05, AddD(D14, D05), SubD(D14, D05), MulD(D14, D05), DivD(D14, D05), LtD(D14, D05), LeD(D14, D05), GtD(D14, D05), GeD(D14, D05), EqD(D14, D05), NeD(D14, D05), MinD(D14, D05), MaxD(D14, D05));
  PairD(240600, D14, D06, AddD(D14, D06), SubD(D14, D06), MulD(D14, D06), DivD(D14, D06), LtD(D14, D06), LeD(D14, D06), GtD(D14, D06), GeD(D14, D06), EqD(D14, D06), NeD(D14, D06), MinD(D14, D06), MaxD(D14, D06));
  PairD(240700, D14, D07, AddD(D14, D07), SubD(D14, D07), MulD(D14, D07), DivD(D14, D07), LtD(D14, D07), LeD(D14, D07), GtD(D14, D07), GeD(D14, D07), EqD(D14, D07), NeD(D14, D07), MinD(D14, D07), MaxD(D14, D07));
  PairD(240800, D14, D08, AddD(D14, D08), SubD(D14, D08), MulD(D14, D08), DivD(D14, D08), LtD(D14, D08), LeD(D14, D08), GtD(D14, D08), GeD(D14, D08), EqD(D14, D08), NeD(D14, D08), MinD(D14, D08), MaxD(D14, D08));
  PairD(240900, D14, D09, AddD(D14, D09), SubD(D14, D09), MulD(D14, D09), DivD(D14, D09), LtD(D14, D09), LeD(D14, D09), GtD(D14, D09), GeD(D14, D09), EqD(D14, D09), NeD(D14, D09), MinD(D14, D09), MaxD(D14, D09));
  PairD(241000, D14, D10, AddD(D14, D10), SubD(D14, D10), MulD(D14, D10), DivD(D14, D10), LtD(D14, D10), LeD(D14, D10), GtD(D14, D10), GeD(D14, D10), EqD(D14, D10), NeD(D14, D10), MinD(D14, D10), MaxD(D14, D10));
  PairD(241100, D14, D11, AddD(D14, D11), SubD(D14, D11), MulD(D14, D11), DivD(D14, D11), LtD(D14, D11), LeD(D14, D11), GtD(D14, D11), GeD(D14, D11), EqD(D14, D11), NeD(D14, D11), MinD(D14, D11), MaxD(D14, D11));
  PairD(241200, D14, D12, AddD(D14, D12), SubD(D14, D12), MulD(D14, D12), DivD(D14, D12), LtD(D14, D12), LeD(D14, D12), GtD(D14, D12), GeD(D14, D12), EqD(D14, D12), NeD(D14, D12), MinD(D14, D12), MaxD(D14, D12));
  PairD(241300, D14, D13, AddD(D14, D13), SubD(D14, D13), MulD(D14, D13), DivD(D14, D13), LtD(D14, D13), LeD(D14, D13), GtD(D14, D13), GeD(D14, D13), EqD(D14, D13), NeD(D14, D13), MinD(D14, D13), MaxD(D14, D13));
  PairD(241400, D14, D14, AddD(D14, D14), SubD(D14, D14), MulD(D14, D14), DivD(D14, D14), LtD(D14, D14), LeD(D14, D14), GtD(D14, D14), GeD(D14, D14), EqD(D14, D14), NeD(D14, D14), MinD(D14, D14), MaxD(D14, D14));
  PairD(241500, D14, D15, AddD(D14, D15), SubD(D14, D15), MulD(D14, D15), DivD(D14, D15), LtD(D14, D15), LeD(D14, D15), GtD(D14, D15), GeD(D14, D15), EqD(D14, D15), NeD(D14, D15), MinD(D14, D15), MaxD(D14, D15));
  PairD(250000, D15, D00, AddD(D15, D00), SubD(D15, D00), MulD(D15, D00), DivD(D15, D00), LtD(D15, D00), LeD(D15, D00), GtD(D15, D00), GeD(D15, D00), EqD(D15, D00), NeD(D15, D00), MinD(D15, D00), MaxD(D15, D00));
  PairD(250100, D15, D01, AddD(D15, D01), SubD(D15, D01), MulD(D15, D01), DivD(D15, D01), LtD(D15, D01), LeD(D15, D01), GtD(D15, D01), GeD(D15, D01), EqD(D15, D01), NeD(D15, D01), MinD(D15, D01), MaxD(D15, D01));
  PairD(250200, D15, D02, AddD(D15, D02), SubD(D15, D02), MulD(D15, D02), DivD(D15, D02), LtD(D15, D02), LeD(D15, D02), GtD(D15, D02), GeD(D15, D02), EqD(D15, D02), NeD(D15, D02), MinD(D15, D02), MaxD(D15, D02));
  PairD(250300, D15, D03, AddD(D15, D03), SubD(D15, D03), MulD(D15, D03), DivD(D15, D03), LtD(D15, D03), LeD(D15, D03), GtD(D15, D03), GeD(D15, D03), EqD(D15, D03), NeD(D15, D03), MinD(D15, D03), MaxD(D15, D03));
  PairD(250400, D15, D04, AddD(D15, D04), SubD(D15, D04), MulD(D15, D04), DivD(D15, D04), LtD(D15, D04), LeD(D15, D04), GtD(D15, D04), GeD(D15, D04), EqD(D15, D04), NeD(D15, D04), MinD(D15, D04), MaxD(D15, D04));
  PairD(250500, D15, D05, AddD(D15, D05), SubD(D15, D05), MulD(D15, D05), DivD(D15, D05), LtD(D15, D05), LeD(D15, D05), GtD(D15, D05), GeD(D15, D05), EqD(D15, D05), NeD(D15, D05), MinD(D15, D05), MaxD(D15, D05));
  PairD(250600, D15, D06, AddD(D15, D06), SubD(D15, D06), MulD(D15, D06), DivD(D15, D06), LtD(D15, D06), LeD(D15, D06), GtD(D15, D06), GeD(D15, D06), EqD(D15, D06), NeD(D15, D06), MinD(D15, D06), MaxD(D15, D06));
  PairD(250700, D15, D07, AddD(D15, D07), SubD(D15, D07), MulD(D15, D07), DivD(D15, D07), LtD(D15, D07), LeD(D15, D07), GtD(D15, D07), GeD(D15, D07), EqD(D15, D07), NeD(D15, D07), MinD(D15, D07), MaxD(D15, D07));
  PairD(250800, D15, D08, AddD(D15, D08), SubD(D15, D08), MulD(D15, D08), DivD(D15, D08), LtD(D15, D08), LeD(D15, D08), GtD(D15, D08), GeD(D15, D08), EqD(D15, D08), NeD(D15, D08), MinD(D15, D08), MaxD(D15, D08));
  PairD(250900, D15, D09, AddD(D15, D09), SubD(D15, D09), MulD(D15, D09), DivD(D15, D09), LtD(D15, D09), LeD(D15, D09), GtD(D15, D09), GeD(D15, D09), EqD(D15, D09), NeD(D15, D09), MinD(D15, D09), MaxD(D15, D09));
  PairD(251000, D15, D10, AddD(D15, D10), SubD(D15, D10), MulD(D15, D10), DivD(D15, D10), LtD(D15, D10), LeD(D15, D10), GtD(D15, D10), GeD(D15, D10), EqD(D15, D10), NeD(D15, D10), MinD(D15, D10), MaxD(D15, D10));
  PairD(251100, D15, D11, AddD(D15, D11), SubD(D15, D11), MulD(D15, D11), DivD(D15, D11), LtD(D15, D11), LeD(D15, D11), GtD(D15, D11), GeD(D15, D11), EqD(D15, D11), NeD(D15, D11), MinD(D15, D11), MaxD(D15, D11));
  PairD(251200, D15, D12, AddD(D15, D12), SubD(D15, D12), MulD(D15, D12), DivD(D15, D12), LtD(D15, D12), LeD(D15, D12), GtD(D15, D12), GeD(D15, D12), EqD(D15, D12), NeD(D15, D12), MinD(D15, D12), MaxD(D15, D12));
  PairD(251300, D15, D13, AddD(D15, D13), SubD(D15, D13), MulD(D15, D13), DivD(D15, D13), LtD(D15, D13), LeD(D15, D13), GtD(D15, D13), GeD(D15, D13), EqD(D15, D13), NeD(D15, D13), MinD(D15, D13), MaxD(D15, D13));
  PairD(251400, D15, D14, AddD(D15, D14), SubD(D15, D14), MulD(D15, D14), DivD(D15, D14), LtD(D15, D14), LeD(D15, D14), GtD(D15, D14), GeD(D15, D14), EqD(D15, D14), NeD(D15, D14), MinD(D15, D14), MaxD(D15, D14));
  PairD(251500, D15, D15, AddD(D15, D15), SubD(D15, D15), MulD(D15, D15), DivD(D15, D15), LtD(D15, D15), LeD(D15, D15), GtD(D15, D15), GeD(D15, D15), EqD(D15, D15), NeD(D15, D15), MinD(D15, D15), MaxD(D15, D15));
  UnaryD(700000, D00, SqrD(D00), SqrtD(D00), FracD(D00), IntD(D00), ExpD(D00), LnD(D00), SinD(D00), CosD(D00), ArcTanD(D00), AbsD(D00), TruncD(D00), DToS(D00));
  UnaryD(700100, D01, SqrD(D01), SqrtD(D01), FracD(D01), IntD(D01), ExpD(D01), LnD(D01), SinD(D01), CosD(D01), ArcTanD(D01), AbsD(D01), TruncD(D01), DToS(D01));
  UnaryD(700200, D02, SqrD(D02), SqrtD(D02), FracD(D02), IntD(D02), ExpD(D02), LnD(D02), SinD(D02), CosD(D02), ArcTanD(D02), AbsD(D02), TruncD(D02), DToS(D02));
  UnaryD(700300, D03, SqrD(D03), SqrtD(D03), FracD(D03), IntD(D03), ExpD(D03), LnD(D03), SinD(D03), CosD(D03), ArcTanD(D03), AbsD(D03), TruncD(D03), DToS(D03));
  UnaryD(700400, D04, SqrD(D04), SqrtD(D04), FracD(D04), IntD(D04), ExpD(D04), LnD(D04), SinD(D04), CosD(D04), ArcTanD(D04), AbsD(D04), TruncD(D04), DToS(D04));
  UnaryD(700500, D05, SqrD(D05), SqrtD(D05), FracD(D05), IntD(D05), ExpD(D05), LnD(D05), SinD(D05), CosD(D05), ArcTanD(D05), AbsD(D05), TruncD(D05), DToS(D05));
  UnaryD(700600, D06, SqrD(D06), SqrtD(D06), FracD(D06), IntD(D06), ExpD(D06), LnD(D06), SinD(D06), CosD(D06), ArcTanD(D06), AbsD(D06), TruncD(D06), DToS(D06));
  UnaryD(700700, D07, SqrD(D07), SqrtD(D07), FracD(D07), IntD(D07), ExpD(D07), LnD(D07), SinD(D07), CosD(D07), ArcTanD(D07), AbsD(D07), 0, DToS(D07));
  UnaryD(700800, D08, SqrD(D08), SqrtD(D08), FracD(D08), IntD(D08), ExpD(D08), LnD(D08), SinD(D08), CosD(D08), ArcTanD(D08), AbsD(D08), TruncD(D08), DToS(D08));
  UnaryD(700900, D09, SqrD(D09), SqrtD(D09), FracD(D09), IntD(D09), ExpD(D09), LnD(D09), SinD(D09), CosD(D09), ArcTanD(D09), AbsD(D09), TruncD(D09), DToS(D09));
  UnaryD(701000, D10, SqrD(D10), SqrtD(D10), FracD(D10), IntD(D10), ExpD(D10), LnD(D10), SinD(D10), CosD(D10), ArcTanD(D10), AbsD(D10), 0, DToS(D10));
  UnaryD(701100, D11, SqrD(D11), SqrtD(D11), FracD(D11), IntD(D11), ExpD(D11), LnD(D11), SinD(D11), CosD(D11), ArcTanD(D11), AbsD(D11), 0, DToS(D11));
  UnaryD(701200, D12, SqrD(D12), SqrtD(D12), FracD(D12), IntD(D12), ExpD(D12), LnD(D12), SinD(D12), CosD(D12), ArcTanD(D12), AbsD(D12), 0, DToS(D12));
  UnaryD(701300, D13, SqrD(D13), SqrtD(D13), FracD(D13), IntD(D13), ExpD(D13), LnD(D13), SinD(D13), CosD(D13), ArcTanD(D13), AbsD(D13), TruncD(D13), DToS(D13));
  UnaryD(701400, D14, SqrD(D14), SqrtD(D14), FracD(D14), IntD(D14), ExpD(D14), LnD(D14), SinD(D14), CosD(D14), ArcTanD(D14), AbsD(D14), TruncD(D14), DToS(D14));
  UnaryD(701500, D15, SqrD(D15), SqrtD(D15), FracD(D15), IntD(D15), ExpD(D15), LnD(D15), SinD(D15), CosD(D15), ArcTanD(D15), AbsD(D15), TruncD(D15), DToS(D15));
end;

procedure RunPairsS;
begin
  PairS(400000, S00, S00, AddS(S00, S00), SubS(S00, S00), MulS(S00, S00), DivS(S00, S00), LtS(S00, S00), EqS(S00, S00), MinS(S00, S00), MaxS(S00, S00));
  PairS(400100, S00, S01, AddS(S00, S01), SubS(S00, S01), MulS(S00, S01), DivS(S00, S01), LtS(S00, S01), EqS(S00, S01), MinS(S00, S01), MaxS(S00, S01));
  PairS(400200, S00, S02, AddS(S00, S02), SubS(S00, S02), MulS(S00, S02), DivS(S00, S02), LtS(S00, S02), EqS(S00, S02), MinS(S00, S02), MaxS(S00, S02));
  PairS(400300, S00, S03, AddS(S00, S03), SubS(S00, S03), MulS(S00, S03), DivS(S00, S03), LtS(S00, S03), EqS(S00, S03), MinS(S00, S03), MaxS(S00, S03));
  PairS(400400, S00, S04, AddS(S00, S04), SubS(S00, S04), MulS(S00, S04), DivS(S00, S04), LtS(S00, S04), EqS(S00, S04), MinS(S00, S04), MaxS(S00, S04));
  PairS(400500, S00, S05, AddS(S00, S05), SubS(S00, S05), MulS(S00, S05), DivS(S00, S05), LtS(S00, S05), EqS(S00, S05), MinS(S00, S05), MaxS(S00, S05));
  PairS(400600, S00, S06, AddS(S00, S06), SubS(S00, S06), MulS(S00, S06), DivS(S00, S06), LtS(S00, S06), EqS(S00, S06), MinS(S00, S06), MaxS(S00, S06));
  PairS(400700, S00, S07, AddS(S00, S07), SubS(S00, S07), MulS(S00, S07), DivS(S00, S07), LtS(S00, S07), EqS(S00, S07), MinS(S00, S07), MaxS(S00, S07));
  PairS(400800, S00, S08, AddS(S00, S08), SubS(S00, S08), MulS(S00, S08), DivS(S00, S08), LtS(S00, S08), EqS(S00, S08), MinS(S00, S08), MaxS(S00, S08));
  PairS(400900, S00, S09, AddS(S00, S09), SubS(S00, S09), MulS(S00, S09), DivS(S00, S09), LtS(S00, S09), EqS(S00, S09), MinS(S00, S09), MaxS(S00, S09));
  PairS(401000, S00, S10, AddS(S00, S10), SubS(S00, S10), MulS(S00, S10), DivS(S00, S10), LtS(S00, S10), EqS(S00, S10), MinS(S00, S10), MaxS(S00, S10));
  PairS(401100, S00, S11, AddS(S00, S11), SubS(S00, S11), MulS(S00, S11), DivS(S00, S11), LtS(S00, S11), EqS(S00, S11), MinS(S00, S11), MaxS(S00, S11));
  PairS(410000, S01, S00, AddS(S01, S00), SubS(S01, S00), MulS(S01, S00), DivS(S01, S00), LtS(S01, S00), EqS(S01, S00), MinS(S01, S00), MaxS(S01, S00));
  PairS(410100, S01, S01, AddS(S01, S01), SubS(S01, S01), MulS(S01, S01), DivS(S01, S01), LtS(S01, S01), EqS(S01, S01), MinS(S01, S01), MaxS(S01, S01));
  PairS(410200, S01, S02, AddS(S01, S02), SubS(S01, S02), MulS(S01, S02), DivS(S01, S02), LtS(S01, S02), EqS(S01, S02), MinS(S01, S02), MaxS(S01, S02));
  PairS(410300, S01, S03, AddS(S01, S03), SubS(S01, S03), MulS(S01, S03), DivS(S01, S03), LtS(S01, S03), EqS(S01, S03), MinS(S01, S03), MaxS(S01, S03));
  PairS(410400, S01, S04, AddS(S01, S04), SubS(S01, S04), MulS(S01, S04), DivS(S01, S04), LtS(S01, S04), EqS(S01, S04), MinS(S01, S04), MaxS(S01, S04));
  PairS(410500, S01, S05, AddS(S01, S05), SubS(S01, S05), MulS(S01, S05), DivS(S01, S05), LtS(S01, S05), EqS(S01, S05), MinS(S01, S05), MaxS(S01, S05));
  PairS(410600, S01, S06, AddS(S01, S06), SubS(S01, S06), MulS(S01, S06), DivS(S01, S06), LtS(S01, S06), EqS(S01, S06), MinS(S01, S06), MaxS(S01, S06));
  PairS(410700, S01, S07, AddS(S01, S07), SubS(S01, S07), MulS(S01, S07), DivS(S01, S07), LtS(S01, S07), EqS(S01, S07), MinS(S01, S07), MaxS(S01, S07));
  PairS(410800, S01, S08, AddS(S01, S08), SubS(S01, S08), MulS(S01, S08), DivS(S01, S08), LtS(S01, S08), EqS(S01, S08), MinS(S01, S08), MaxS(S01, S08));
  PairS(410900, S01, S09, AddS(S01, S09), SubS(S01, S09), MulS(S01, S09), DivS(S01, S09), LtS(S01, S09), EqS(S01, S09), MinS(S01, S09), MaxS(S01, S09));
  PairS(411000, S01, S10, AddS(S01, S10), SubS(S01, S10), MulS(S01, S10), DivS(S01, S10), LtS(S01, S10), EqS(S01, S10), MinS(S01, S10), MaxS(S01, S10));
  PairS(411100, S01, S11, AddS(S01, S11), SubS(S01, S11), MulS(S01, S11), DivS(S01, S11), LtS(S01, S11), EqS(S01, S11), MinS(S01, S11), MaxS(S01, S11));
  PairS(420000, S02, S00, AddS(S02, S00), SubS(S02, S00), MulS(S02, S00), DivS(S02, S00), LtS(S02, S00), EqS(S02, S00), MinS(S02, S00), MaxS(S02, S00));
  PairS(420100, S02, S01, AddS(S02, S01), SubS(S02, S01), MulS(S02, S01), DivS(S02, S01), LtS(S02, S01), EqS(S02, S01), MinS(S02, S01), MaxS(S02, S01));
  PairS(420200, S02, S02, AddS(S02, S02), SubS(S02, S02), MulS(S02, S02), DivS(S02, S02), LtS(S02, S02), EqS(S02, S02), MinS(S02, S02), MaxS(S02, S02));
  PairS(420300, S02, S03, AddS(S02, S03), SubS(S02, S03), MulS(S02, S03), DivS(S02, S03), LtS(S02, S03), EqS(S02, S03), MinS(S02, S03), MaxS(S02, S03));
  PairS(420400, S02, S04, AddS(S02, S04), SubS(S02, S04), MulS(S02, S04), DivS(S02, S04), LtS(S02, S04), EqS(S02, S04), MinS(S02, S04), MaxS(S02, S04));
  PairS(420500, S02, S05, AddS(S02, S05), SubS(S02, S05), MulS(S02, S05), DivS(S02, S05), LtS(S02, S05), EqS(S02, S05), MinS(S02, S05), MaxS(S02, S05));
  PairS(420600, S02, S06, AddS(S02, S06), SubS(S02, S06), MulS(S02, S06), DivS(S02, S06), LtS(S02, S06), EqS(S02, S06), MinS(S02, S06), MaxS(S02, S06));
  PairS(420700, S02, S07, AddS(S02, S07), SubS(S02, S07), MulS(S02, S07), DivS(S02, S07), LtS(S02, S07), EqS(S02, S07), MinS(S02, S07), MaxS(S02, S07));
  PairS(420800, S02, S08, AddS(S02, S08), SubS(S02, S08), MulS(S02, S08), DivS(S02, S08), LtS(S02, S08), EqS(S02, S08), MinS(S02, S08), MaxS(S02, S08));
  PairS(420900, S02, S09, AddS(S02, S09), SubS(S02, S09), MulS(S02, S09), DivS(S02, S09), LtS(S02, S09), EqS(S02, S09), MinS(S02, S09), MaxS(S02, S09));
  PairS(421000, S02, S10, AddS(S02, S10), SubS(S02, S10), MulS(S02, S10), DivS(S02, S10), LtS(S02, S10), EqS(S02, S10), MinS(S02, S10), MaxS(S02, S10));
  PairS(421100, S02, S11, AddS(S02, S11), SubS(S02, S11), MulS(S02, S11), DivS(S02, S11), LtS(S02, S11), EqS(S02, S11), MinS(S02, S11), MaxS(S02, S11));
  PairS(430000, S03, S00, AddS(S03, S00), SubS(S03, S00), MulS(S03, S00), DivS(S03, S00), LtS(S03, S00), EqS(S03, S00), MinS(S03, S00), MaxS(S03, S00));
  PairS(430100, S03, S01, AddS(S03, S01), SubS(S03, S01), MulS(S03, S01), DivS(S03, S01), LtS(S03, S01), EqS(S03, S01), MinS(S03, S01), MaxS(S03, S01));
  PairS(430200, S03, S02, AddS(S03, S02), SubS(S03, S02), MulS(S03, S02), DivS(S03, S02), LtS(S03, S02), EqS(S03, S02), MinS(S03, S02), MaxS(S03, S02));
  PairS(430300, S03, S03, AddS(S03, S03), SubS(S03, S03), MulS(S03, S03), DivS(S03, S03), LtS(S03, S03), EqS(S03, S03), MinS(S03, S03), MaxS(S03, S03));
  PairS(430400, S03, S04, AddS(S03, S04), SubS(S03, S04), MulS(S03, S04), DivS(S03, S04), LtS(S03, S04), EqS(S03, S04), MinS(S03, S04), MaxS(S03, S04));
  PairS(430500, S03, S05, AddS(S03, S05), SubS(S03, S05), MulS(S03, S05), DivS(S03, S05), LtS(S03, S05), EqS(S03, S05), MinS(S03, S05), MaxS(S03, S05));
  PairS(430600, S03, S06, AddS(S03, S06), SubS(S03, S06), MulS(S03, S06), DivS(S03, S06), LtS(S03, S06), EqS(S03, S06), MinS(S03, S06), MaxS(S03, S06));
  PairS(430700, S03, S07, AddS(S03, S07), SubS(S03, S07), MulS(S03, S07), DivS(S03, S07), LtS(S03, S07), EqS(S03, S07), MinS(S03, S07), MaxS(S03, S07));
  PairS(430800, S03, S08, AddS(S03, S08), SubS(S03, S08), MulS(S03, S08), DivS(S03, S08), LtS(S03, S08), EqS(S03, S08), MinS(S03, S08), MaxS(S03, S08));
  PairS(430900, S03, S09, AddS(S03, S09), SubS(S03, S09), MulS(S03, S09), DivS(S03, S09), LtS(S03, S09), EqS(S03, S09), MinS(S03, S09), MaxS(S03, S09));
  PairS(431000, S03, S10, AddS(S03, S10), SubS(S03, S10), MulS(S03, S10), DivS(S03, S10), LtS(S03, S10), EqS(S03, S10), MinS(S03, S10), MaxS(S03, S10));
  PairS(431100, S03, S11, AddS(S03, S11), SubS(S03, S11), MulS(S03, S11), DivS(S03, S11), LtS(S03, S11), EqS(S03, S11), MinS(S03, S11), MaxS(S03, S11));
  PairS(440000, S04, S00, AddS(S04, S00), SubS(S04, S00), MulS(S04, S00), DivS(S04, S00), LtS(S04, S00), EqS(S04, S00), MinS(S04, S00), MaxS(S04, S00));
  PairS(440100, S04, S01, AddS(S04, S01), SubS(S04, S01), MulS(S04, S01), DivS(S04, S01), LtS(S04, S01), EqS(S04, S01), MinS(S04, S01), MaxS(S04, S01));
  PairS(440200, S04, S02, AddS(S04, S02), SubS(S04, S02), MulS(S04, S02), DivS(S04, S02), LtS(S04, S02), EqS(S04, S02), MinS(S04, S02), MaxS(S04, S02));
  PairS(440300, S04, S03, AddS(S04, S03), SubS(S04, S03), MulS(S04, S03), DivS(S04, S03), LtS(S04, S03), EqS(S04, S03), MinS(S04, S03), MaxS(S04, S03));
  PairS(440400, S04, S04, AddS(S04, S04), SubS(S04, S04), MulS(S04, S04), DivS(S04, S04), LtS(S04, S04), EqS(S04, S04), MinS(S04, S04), MaxS(S04, S04));
  PairS(440500, S04, S05, AddS(S04, S05), SubS(S04, S05), MulS(S04, S05), DivS(S04, S05), LtS(S04, S05), EqS(S04, S05), MinS(S04, S05), MaxS(S04, S05));
  PairS(440600, S04, S06, AddS(S04, S06), SubS(S04, S06), MulS(S04, S06), DivS(S04, S06), LtS(S04, S06), EqS(S04, S06), MinS(S04, S06), MaxS(S04, S06));
  PairS(440700, S04, S07, AddS(S04, S07), SubS(S04, S07), MulS(S04, S07), DivS(S04, S07), LtS(S04, S07), EqS(S04, S07), MinS(S04, S07), MaxS(S04, S07));
  PairS(440800, S04, S08, AddS(S04, S08), SubS(S04, S08), MulS(S04, S08), DivS(S04, S08), LtS(S04, S08), EqS(S04, S08), MinS(S04, S08), MaxS(S04, S08));
  PairS(440900, S04, S09, AddS(S04, S09), SubS(S04, S09), MulS(S04, S09), DivS(S04, S09), LtS(S04, S09), EqS(S04, S09), MinS(S04, S09), MaxS(S04, S09));
  PairS(441000, S04, S10, AddS(S04, S10), SubS(S04, S10), MulS(S04, S10), DivS(S04, S10), LtS(S04, S10), EqS(S04, S10), MinS(S04, S10), MaxS(S04, S10));
  PairS(441100, S04, S11, AddS(S04, S11), SubS(S04, S11), MulS(S04, S11), DivS(S04, S11), LtS(S04, S11), EqS(S04, S11), MinS(S04, S11), MaxS(S04, S11));
  PairS(450000, S05, S00, AddS(S05, S00), SubS(S05, S00), MulS(S05, S00), DivS(S05, S00), LtS(S05, S00), EqS(S05, S00), MinS(S05, S00), MaxS(S05, S00));
  PairS(450100, S05, S01, AddS(S05, S01), SubS(S05, S01), MulS(S05, S01), DivS(S05, S01), LtS(S05, S01), EqS(S05, S01), MinS(S05, S01), MaxS(S05, S01));
  PairS(450200, S05, S02, AddS(S05, S02), SubS(S05, S02), MulS(S05, S02), DivS(S05, S02), LtS(S05, S02), EqS(S05, S02), MinS(S05, S02), MaxS(S05, S02));
  PairS(450300, S05, S03, AddS(S05, S03), SubS(S05, S03), MulS(S05, S03), DivS(S05, S03), LtS(S05, S03), EqS(S05, S03), MinS(S05, S03), MaxS(S05, S03));
  PairS(450400, S05, S04, AddS(S05, S04), SubS(S05, S04), MulS(S05, S04), DivS(S05, S04), LtS(S05, S04), EqS(S05, S04), MinS(S05, S04), MaxS(S05, S04));
  PairS(450500, S05, S05, AddS(S05, S05), SubS(S05, S05), MulS(S05, S05), DivS(S05, S05), LtS(S05, S05), EqS(S05, S05), MinS(S05, S05), MaxS(S05, S05));
  PairS(450600, S05, S06, AddS(S05, S06), SubS(S05, S06), MulS(S05, S06), DivS(S05, S06), LtS(S05, S06), EqS(S05, S06), MinS(S05, S06), MaxS(S05, S06));
  PairS(450700, S05, S07, AddS(S05, S07), SubS(S05, S07), MulS(S05, S07), DivS(S05, S07), LtS(S05, S07), EqS(S05, S07), MinS(S05, S07), MaxS(S05, S07));
  PairS(450800, S05, S08, AddS(S05, S08), SubS(S05, S08), MulS(S05, S08), DivS(S05, S08), LtS(S05, S08), EqS(S05, S08), MinS(S05, S08), MaxS(S05, S08));
  PairS(450900, S05, S09, AddS(S05, S09), SubS(S05, S09), MulS(S05, S09), DivS(S05, S09), LtS(S05, S09), EqS(S05, S09), MinS(S05, S09), MaxS(S05, S09));
  PairS(451000, S05, S10, AddS(S05, S10), SubS(S05, S10), MulS(S05, S10), DivS(S05, S10), LtS(S05, S10), EqS(S05, S10), MinS(S05, S10), MaxS(S05, S10));
  PairS(451100, S05, S11, AddS(S05, S11), SubS(S05, S11), MulS(S05, S11), DivS(S05, S11), LtS(S05, S11), EqS(S05, S11), MinS(S05, S11), MaxS(S05, S11));
  PairS(460000, S06, S00, AddS(S06, S00), SubS(S06, S00), MulS(S06, S00), DivS(S06, S00), LtS(S06, S00), EqS(S06, S00), MinS(S06, S00), MaxS(S06, S00));
  PairS(460100, S06, S01, AddS(S06, S01), SubS(S06, S01), MulS(S06, S01), DivS(S06, S01), LtS(S06, S01), EqS(S06, S01), MinS(S06, S01), MaxS(S06, S01));
  PairS(460200, S06, S02, AddS(S06, S02), SubS(S06, S02), MulS(S06, S02), DivS(S06, S02), LtS(S06, S02), EqS(S06, S02), MinS(S06, S02), MaxS(S06, S02));
  PairS(460300, S06, S03, AddS(S06, S03), SubS(S06, S03), MulS(S06, S03), DivS(S06, S03), LtS(S06, S03), EqS(S06, S03), MinS(S06, S03), MaxS(S06, S03));
  PairS(460400, S06, S04, AddS(S06, S04), SubS(S06, S04), MulS(S06, S04), DivS(S06, S04), LtS(S06, S04), EqS(S06, S04), MinS(S06, S04), MaxS(S06, S04));
  PairS(460500, S06, S05, AddS(S06, S05), SubS(S06, S05), MulS(S06, S05), DivS(S06, S05), LtS(S06, S05), EqS(S06, S05), MinS(S06, S05), MaxS(S06, S05));
  PairS(460600, S06, S06, AddS(S06, S06), SubS(S06, S06), MulS(S06, S06), DivS(S06, S06), LtS(S06, S06), EqS(S06, S06), MinS(S06, S06), MaxS(S06, S06));
  PairS(460700, S06, S07, AddS(S06, S07), SubS(S06, S07), MulS(S06, S07), DivS(S06, S07), LtS(S06, S07), EqS(S06, S07), MinS(S06, S07), MaxS(S06, S07));
  PairS(460800, S06, S08, AddS(S06, S08), SubS(S06, S08), MulS(S06, S08), DivS(S06, S08), LtS(S06, S08), EqS(S06, S08), MinS(S06, S08), MaxS(S06, S08));
  PairS(460900, S06, S09, AddS(S06, S09), SubS(S06, S09), MulS(S06, S09), DivS(S06, S09), LtS(S06, S09), EqS(S06, S09), MinS(S06, S09), MaxS(S06, S09));
  PairS(461000, S06, S10, AddS(S06, S10), SubS(S06, S10), MulS(S06, S10), DivS(S06, S10), LtS(S06, S10), EqS(S06, S10), MinS(S06, S10), MaxS(S06, S10));
  PairS(461100, S06, S11, AddS(S06, S11), SubS(S06, S11), MulS(S06, S11), DivS(S06, S11), LtS(S06, S11), EqS(S06, S11), MinS(S06, S11), MaxS(S06, S11));
  PairS(470000, S07, S00, AddS(S07, S00), SubS(S07, S00), MulS(S07, S00), DivS(S07, S00), LtS(S07, S00), EqS(S07, S00), MinS(S07, S00), MaxS(S07, S00));
  PairS(470100, S07, S01, AddS(S07, S01), SubS(S07, S01), MulS(S07, S01), DivS(S07, S01), LtS(S07, S01), EqS(S07, S01), MinS(S07, S01), MaxS(S07, S01));
  PairS(470200, S07, S02, AddS(S07, S02), SubS(S07, S02), MulS(S07, S02), DivS(S07, S02), LtS(S07, S02), EqS(S07, S02), MinS(S07, S02), MaxS(S07, S02));
  PairS(470300, S07, S03, AddS(S07, S03), SubS(S07, S03), MulS(S07, S03), DivS(S07, S03), LtS(S07, S03), EqS(S07, S03), MinS(S07, S03), MaxS(S07, S03));
  PairS(470400, S07, S04, AddS(S07, S04), SubS(S07, S04), MulS(S07, S04), DivS(S07, S04), LtS(S07, S04), EqS(S07, S04), MinS(S07, S04), MaxS(S07, S04));
  PairS(470500, S07, S05, AddS(S07, S05), SubS(S07, S05), MulS(S07, S05), DivS(S07, S05), LtS(S07, S05), EqS(S07, S05), MinS(S07, S05), MaxS(S07, S05));
  PairS(470600, S07, S06, AddS(S07, S06), SubS(S07, S06), MulS(S07, S06), DivS(S07, S06), LtS(S07, S06), EqS(S07, S06), MinS(S07, S06), MaxS(S07, S06));
  PairS(470700, S07, S07, AddS(S07, S07), SubS(S07, S07), MulS(S07, S07), DivS(S07, S07), LtS(S07, S07), EqS(S07, S07), MinS(S07, S07), MaxS(S07, S07));
  PairS(470800, S07, S08, AddS(S07, S08), SubS(S07, S08), MulS(S07, S08), DivS(S07, S08), LtS(S07, S08), EqS(S07, S08), MinS(S07, S08), MaxS(S07, S08));
  PairS(470900, S07, S09, AddS(S07, S09), SubS(S07, S09), MulS(S07, S09), DivS(S07, S09), LtS(S07, S09), EqS(S07, S09), MinS(S07, S09), MaxS(S07, S09));
  PairS(471000, S07, S10, AddS(S07, S10), SubS(S07, S10), MulS(S07, S10), DivS(S07, S10), LtS(S07, S10), EqS(S07, S10), MinS(S07, S10), MaxS(S07, S10));
  PairS(471100, S07, S11, AddS(S07, S11), SubS(S07, S11), MulS(S07, S11), DivS(S07, S11), LtS(S07, S11), EqS(S07, S11), MinS(S07, S11), MaxS(S07, S11));
  PairS(480000, S08, S00, AddS(S08, S00), SubS(S08, S00), MulS(S08, S00), DivS(S08, S00), LtS(S08, S00), EqS(S08, S00), MinS(S08, S00), MaxS(S08, S00));
  PairS(480100, S08, S01, AddS(S08, S01), SubS(S08, S01), MulS(S08, S01), DivS(S08, S01), LtS(S08, S01), EqS(S08, S01), MinS(S08, S01), MaxS(S08, S01));
  PairS(480200, S08, S02, AddS(S08, S02), SubS(S08, S02), MulS(S08, S02), DivS(S08, S02), LtS(S08, S02), EqS(S08, S02), MinS(S08, S02), MaxS(S08, S02));
  PairS(480300, S08, S03, AddS(S08, S03), SubS(S08, S03), MulS(S08, S03), DivS(S08, S03), LtS(S08, S03), EqS(S08, S03), MinS(S08, S03), MaxS(S08, S03));
  PairS(480400, S08, S04, AddS(S08, S04), SubS(S08, S04), MulS(S08, S04), DivS(S08, S04), LtS(S08, S04), EqS(S08, S04), MinS(S08, S04), MaxS(S08, S04));
  PairS(480500, S08, S05, AddS(S08, S05), SubS(S08, S05), MulS(S08, S05), DivS(S08, S05), LtS(S08, S05), EqS(S08, S05), MinS(S08, S05), MaxS(S08, S05));
  PairS(480600, S08, S06, AddS(S08, S06), SubS(S08, S06), MulS(S08, S06), DivS(S08, S06), LtS(S08, S06), EqS(S08, S06), MinS(S08, S06), MaxS(S08, S06));
  PairS(480700, S08, S07, AddS(S08, S07), SubS(S08, S07), MulS(S08, S07), DivS(S08, S07), LtS(S08, S07), EqS(S08, S07), MinS(S08, S07), MaxS(S08, S07));
  PairS(480800, S08, S08, AddS(S08, S08), SubS(S08, S08), MulS(S08, S08), DivS(S08, S08), LtS(S08, S08), EqS(S08, S08), MinS(S08, S08), MaxS(S08, S08));
  PairS(480900, S08, S09, AddS(S08, S09), SubS(S08, S09), MulS(S08, S09), DivS(S08, S09), LtS(S08, S09), EqS(S08, S09), MinS(S08, S09), MaxS(S08, S09));
  PairS(481000, S08, S10, AddS(S08, S10), SubS(S08, S10), MulS(S08, S10), DivS(S08, S10), LtS(S08, S10), EqS(S08, S10), MinS(S08, S10), MaxS(S08, S10));
  PairS(481100, S08, S11, AddS(S08, S11), SubS(S08, S11), MulS(S08, S11), DivS(S08, S11), LtS(S08, S11), EqS(S08, S11), MinS(S08, S11), MaxS(S08, S11));
  PairS(490000, S09, S00, AddS(S09, S00), SubS(S09, S00), MulS(S09, S00), DivS(S09, S00), LtS(S09, S00), EqS(S09, S00), MinS(S09, S00), MaxS(S09, S00));
  PairS(490100, S09, S01, AddS(S09, S01), SubS(S09, S01), MulS(S09, S01), DivS(S09, S01), LtS(S09, S01), EqS(S09, S01), MinS(S09, S01), MaxS(S09, S01));
  PairS(490200, S09, S02, AddS(S09, S02), SubS(S09, S02), MulS(S09, S02), DivS(S09, S02), LtS(S09, S02), EqS(S09, S02), MinS(S09, S02), MaxS(S09, S02));
  PairS(490300, S09, S03, AddS(S09, S03), SubS(S09, S03), MulS(S09, S03), DivS(S09, S03), LtS(S09, S03), EqS(S09, S03), MinS(S09, S03), MaxS(S09, S03));
  PairS(490400, S09, S04, AddS(S09, S04), SubS(S09, S04), MulS(S09, S04), DivS(S09, S04), LtS(S09, S04), EqS(S09, S04), MinS(S09, S04), MaxS(S09, S04));
  PairS(490500, S09, S05, AddS(S09, S05), SubS(S09, S05), MulS(S09, S05), DivS(S09, S05), LtS(S09, S05), EqS(S09, S05), MinS(S09, S05), MaxS(S09, S05));
  PairS(490600, S09, S06, AddS(S09, S06), SubS(S09, S06), MulS(S09, S06), DivS(S09, S06), LtS(S09, S06), EqS(S09, S06), MinS(S09, S06), MaxS(S09, S06));
  PairS(490700, S09, S07, AddS(S09, S07), SubS(S09, S07), MulS(S09, S07), DivS(S09, S07), LtS(S09, S07), EqS(S09, S07), MinS(S09, S07), MaxS(S09, S07));
  PairS(490800, S09, S08, AddS(S09, S08), SubS(S09, S08), MulS(S09, S08), DivS(S09, S08), LtS(S09, S08), EqS(S09, S08), MinS(S09, S08), MaxS(S09, S08));
  PairS(490900, S09, S09, AddS(S09, S09), SubS(S09, S09), MulS(S09, S09), DivS(S09, S09), LtS(S09, S09), EqS(S09, S09), MinS(S09, S09), MaxS(S09, S09));
  PairS(491000, S09, S10, AddS(S09, S10), SubS(S09, S10), MulS(S09, S10), DivS(S09, S10), LtS(S09, S10), EqS(S09, S10), MinS(S09, S10), MaxS(S09, S10));
  PairS(491100, S09, S11, AddS(S09, S11), SubS(S09, S11), MulS(S09, S11), DivS(S09, S11), LtS(S09, S11), EqS(S09, S11), MinS(S09, S11), MaxS(S09, S11));
  PairS(500000, S10, S00, AddS(S10, S00), SubS(S10, S00), MulS(S10, S00), DivS(S10, S00), LtS(S10, S00), EqS(S10, S00), MinS(S10, S00), MaxS(S10, S00));
  PairS(500100, S10, S01, AddS(S10, S01), SubS(S10, S01), MulS(S10, S01), DivS(S10, S01), LtS(S10, S01), EqS(S10, S01), MinS(S10, S01), MaxS(S10, S01));
  PairS(500200, S10, S02, AddS(S10, S02), SubS(S10, S02), MulS(S10, S02), DivS(S10, S02), LtS(S10, S02), EqS(S10, S02), MinS(S10, S02), MaxS(S10, S02));
  PairS(500300, S10, S03, AddS(S10, S03), SubS(S10, S03), MulS(S10, S03), DivS(S10, S03), LtS(S10, S03), EqS(S10, S03), MinS(S10, S03), MaxS(S10, S03));
  PairS(500400, S10, S04, AddS(S10, S04), SubS(S10, S04), MulS(S10, S04), DivS(S10, S04), LtS(S10, S04), EqS(S10, S04), MinS(S10, S04), MaxS(S10, S04));
  PairS(500500, S10, S05, AddS(S10, S05), SubS(S10, S05), MulS(S10, S05), DivS(S10, S05), LtS(S10, S05), EqS(S10, S05), MinS(S10, S05), MaxS(S10, S05));
  PairS(500600, S10, S06, AddS(S10, S06), SubS(S10, S06), MulS(S10, S06), DivS(S10, S06), LtS(S10, S06), EqS(S10, S06), MinS(S10, S06), MaxS(S10, S06));
  PairS(500700, S10, S07, AddS(S10, S07), SubS(S10, S07), MulS(S10, S07), DivS(S10, S07), LtS(S10, S07), EqS(S10, S07), MinS(S10, S07), MaxS(S10, S07));
  PairS(500800, S10, S08, AddS(S10, S08), SubS(S10, S08), MulS(S10, S08), DivS(S10, S08), LtS(S10, S08), EqS(S10, S08), MinS(S10, S08), MaxS(S10, S08));
  PairS(500900, S10, S09, AddS(S10, S09), SubS(S10, S09), MulS(S10, S09), DivS(S10, S09), LtS(S10, S09), EqS(S10, S09), MinS(S10, S09), MaxS(S10, S09));
  PairS(501000, S10, S10, AddS(S10, S10), SubS(S10, S10), MulS(S10, S10), DivS(S10, S10), LtS(S10, S10), EqS(S10, S10), MinS(S10, S10), MaxS(S10, S10));
  PairS(501100, S10, S11, AddS(S10, S11), SubS(S10, S11), MulS(S10, S11), DivS(S10, S11), LtS(S10, S11), EqS(S10, S11), MinS(S10, S11), MaxS(S10, S11));
  PairS(510000, S11, S00, AddS(S11, S00), SubS(S11, S00), MulS(S11, S00), DivS(S11, S00), LtS(S11, S00), EqS(S11, S00), MinS(S11, S00), MaxS(S11, S00));
  PairS(510100, S11, S01, AddS(S11, S01), SubS(S11, S01), MulS(S11, S01), DivS(S11, S01), LtS(S11, S01), EqS(S11, S01), MinS(S11, S01), MaxS(S11, S01));
  PairS(510200, S11, S02, AddS(S11, S02), SubS(S11, S02), MulS(S11, S02), DivS(S11, S02), LtS(S11, S02), EqS(S11, S02), MinS(S11, S02), MaxS(S11, S02));
  PairS(510300, S11, S03, AddS(S11, S03), SubS(S11, S03), MulS(S11, S03), DivS(S11, S03), LtS(S11, S03), EqS(S11, S03), MinS(S11, S03), MaxS(S11, S03));
  PairS(510400, S11, S04, AddS(S11, S04), SubS(S11, S04), MulS(S11, S04), DivS(S11, S04), LtS(S11, S04), EqS(S11, S04), MinS(S11, S04), MaxS(S11, S04));
  PairS(510500, S11, S05, AddS(S11, S05), SubS(S11, S05), MulS(S11, S05), DivS(S11, S05), LtS(S11, S05), EqS(S11, S05), MinS(S11, S05), MaxS(S11, S05));
  PairS(510600, S11, S06, AddS(S11, S06), SubS(S11, S06), MulS(S11, S06), DivS(S11, S06), LtS(S11, S06), EqS(S11, S06), MinS(S11, S06), MaxS(S11, S06));
  PairS(510700, S11, S07, AddS(S11, S07), SubS(S11, S07), MulS(S11, S07), DivS(S11, S07), LtS(S11, S07), EqS(S11, S07), MinS(S11, S07), MaxS(S11, S07));
  PairS(510800, S11, S08, AddS(S11, S08), SubS(S11, S08), MulS(S11, S08), DivS(S11, S08), LtS(S11, S08), EqS(S11, S08), MinS(S11, S08), MaxS(S11, S08));
  PairS(510900, S11, S09, AddS(S11, S09), SubS(S11, S09), MulS(S11, S09), DivS(S11, S09), LtS(S11, S09), EqS(S11, S09), MinS(S11, S09), MaxS(S11, S09));
  PairS(511000, S11, S10, AddS(S11, S10), SubS(S11, S10), MulS(S11, S10), DivS(S11, S10), LtS(S11, S10), EqS(S11, S10), MinS(S11, S10), MaxS(S11, S10));
  PairS(511100, S11, S11, AddS(S11, S11), SubS(S11, S11), MulS(S11, S11), DivS(S11, S11), LtS(S11, S11), EqS(S11, S11), MinS(S11, S11), MaxS(S11, S11));
  UnaryS(800000, S00, SqrS(S00), SqrtS(S00), SToD(S00));
  UnaryS(800100, S01, SqrS(S01), SqrtS(S01), SToD(S01));
  UnaryS(800200, S02, SqrS(S02), SqrtS(S02), SToD(S02));
  UnaryS(800300, S03, SqrS(S03), SqrtS(S03), SToD(S03));
  UnaryS(800400, S04, SqrS(S04), SqrtS(S04), SToD(S04));
  UnaryS(800500, S05, SqrS(S05), SqrtS(S05), SToD(S05));
  UnaryS(800600, S06, SqrS(S06), SqrtS(S06), SToD(S06));
  UnaryS(800700, S07, SqrS(S07), SqrtS(S07), SToD(S07));
  UnaryS(800800, S08, SqrS(S08), SqrtS(S08), SToD(S08));
  UnaryS(800900, S09, SqrS(S09), SqrtS(S09), SToD(S09));
  UnaryS(801000, S10, SqrS(S10), SqrtS(S10), SToD(S10));
  UnaryS(801100, S11, SqrS(S11), SqrtS(S11), SToD(S11));
end;


{ min/max over memory: the rewrite into minsd/maxsd against the same choice
  made through a Boolean the rewrite does not see }
function MinScan(const A: array of Double): Double; {$ifdef FPC}noinline;{$endif}
var
  I: Integer;
  M: Double;
begin
  M := A[0];
  for I := 1 to High(A) do
    If A[I] < M then
      M := A[I];
  Result := M;
end;

function MinScanRef(const A: array of Double): Double; {$ifdef FPC}noinline;{$endif}
var
  I: Integer;
  M: Double;
  Take: Boolean;
begin
  M := A[0];
  for I := 1 to High(A) do
  begin
    Take := A[I] < M;
    If Take then
      M := A[I];
  end;
  Result := M;
end;

function MaxScan(const A: array of Double): Double; {$ifdef FPC}noinline;{$endif}
var
  I: Integer;
  M: Double;
begin
  M := A[0];
  for I := 1 to High(A) do
    If A[I] > M then
      M := A[I];
  Result := M;
end;

function MaxScanRef(const A: array of Double): Double; {$ifdef FPC}noinline;{$endif}
var
  I: Integer;
  M: Double;
  Take: Boolean;
begin
  M := A[0];
  for I := 1 to High(A) do
  begin
    Take := A[I] > M;
    If Take then
      M := A[I];
  end;
  Result := M;
end;

procedure Widen(P: PRange; V: Double); {$ifdef FPC}noinline;{$endif}
begin
  If V < P^.Lo then
    P^.Lo := V;
  If V > P^.Hi then
    P^.Hi := V;
end;

procedure WidenRef(P: PRange; V: Double); {$ifdef FPC}noinline;{$endif}
var
  Take: Boolean;
begin
  Take := V < P^.Lo;
  If Take then
    P^.Lo := V;
  Take := V > P^.Hi;
  If Take then
    P^.Hi := V;
end;

procedure LowerElement(var A: array of Double; I: Integer; V: Double); {$ifdef FPC}noinline;{$endif}
begin
  If V < A[I] then
    A[I] := V;
end;

procedure LowerElementRef(var A: array of Double; I: Integer; V: Double); {$ifdef FPC}noinline;{$endif}
var
  Take: Boolean;
begin
  Take := V < A[I];
  If Take then
    A[I] := V;
end;

procedure CheckMemoryMinMax;
var
  Values: array[0..4] of Double;
  A: array[0..2] of Double;
  B: array[0..2] of Double;
  R, RR: TRange;
  I, J, K, Code: Integer;
begin
  Values[0] := 0.0;
  Values[1] := -0.0;
  Values[2] := NaN;
  Values[3] := 1.0;
  Values[4] := -1.0;
  Code := 900000;
  for I := 0 to 4 do
    for J := 0 to 4 do
      for K := 0 to 4 do
      begin
        A[0] := Values[I];
        A[1] := Values[J];
        A[2] := Values[K];
        CD(Code, MinScan(A), MinScanRef(A));
        CD(Code + 1, MaxScan(A), MaxScanRef(A));
        R.Lo := Values[I];
        R.Hi := Values[J];
        RR := R;
        Widen(@R, Values[K]);
        WidenRef(@RR, Values[K]);
        CD(Code + 2, R.Lo, RR.Lo);
        CD(Code + 3, R.Hi, RR.Hi);
        A[0] := Values[I];
        A[1] := Values[J];
        B[0] := Values[I];
        B[1] := Values[J];
        LowerElement(A, 1, Values[K]);
        LowerElementRef(B, 1, Values[K]);
        CD(Code + 4, A[1], B[1]);
        Inc(Code, 10);
      end;
end;

{ An exceptional operand or result keeps the operation at run time: with the
  exception unmasked, the inlined constant operation still raises it. }
var
  Sink: Double;
  SinkS: Single;
  SinkI: Int64;
  SinkB: Boolean;

procedure ExpectTrap(Code: Integer);
var
  Mask: {$ifdef FPC}TFPUExceptionMask{$else}TArithmeticExceptionMask{$endif};
begin
  Mask := GetExceptionMask;
  If Code < 10 then
    SetExceptionMask([exDenormalized, exUnderflow, exPrecision])
  else
    SetExceptionMask([exDenormalized, exPrecision]);
  try
    try
      case Code of
        0: Sink := DivD(1.0, 0.0);
        1: Sink := DivD(0.0, 0.0);
        2: Sink := MulD(1.7976931348623157e308, 2.0);
        3: Sink := SqrtD(-1.0);
        4: Sink := AddD(Infinity, NegInfinity);
        5: Sink := MulD(0.0, Infinity);
        6: SinkS := DToS(1.0e300);
        7: SinkI := TruncD(1.0e30);
        8: SinkB := LtD(NaN, 1.0);
        9: SinkS := MulS(3.0e38, 3.0e38);
        { the exact result lies below the smallest normal number and rounds up
          to it: tiny after rounding with unbounded exponent }
        10: Sink := MulD(4.4501477170144023e-308, 0.5);
        11: Sink := DivD(4.4501477170144023e-308, 2.0);
        12: SinkS := DToS(1.1754942807573643e-38);
        13: SinkS := MulS(2.3509885615147286e-38, 0.5);
      end;
      Fail('trap ' + IntToStr(Code) + ' not raised');
    except
      on EMathError do
        ;
    end;
  finally
    ClearExceptions(False);
    SetExceptionMask(Mask);
  end;
end;

var
  T: Integer;
begin
  Checks := 0;
  Failures := 0;
  RunPairsD;
  RunPairsS;
  CheckMemoryMinMax;
  for T := 0 to 13 do
    ExpectTrap(T);
  WriteLn('checks=', Checks, ' failures=', Failures);
  If Failures <> 0 then
    Halt(1);
  WriteLn('TFOLDRUNTIMEREAL1_PASS');
end.
