unit stand3drivers;

{ generated by gen_drivers.py }

{$mode delphi}{$asmmode intel}

interface

procedure DrvTarget;
function DrvSysvF0Rax(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvSysvF0Eax(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvSysvF0Al(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvSysvF0S32(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvSysvF0None(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvSysvF1Xs(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvSysvF1Rax(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvSysvF1Xd(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;
function DrvMsF1Xd(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default;

implementation

procedure DrvTarget; assembler; nostackframe;
asm
        ret
end;

function DrvSysvF0Rax(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        mov     rdi, qword ptr [rbx + 0]
        mov     rsi, qword ptr [rbx + 8]
        mov     rdx, qword ptr [rbx + 16]
        mov     rcx, qword ptr [rbx + 24]
        call    DrvTarget
        rol     r13, 5
        xor     r13, rax
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvSysvF0Eax(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        mov     rdi, qword ptr [rbx + 0]
        mov     rsi, qword ptr [rbx + 8]
        mov     rdx, qword ptr [rbx + 16]
        mov     rcx, qword ptr [rbx + 24]
        call    DrvTarget
        mov eax, eax
        rol     r13, 5
        xor     r13, rax
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvSysvF0Al(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        mov     rdi, qword ptr [rbx + 0]
        mov     rsi, qword ptr [rbx + 8]
        mov     rdx, qword ptr [rbx + 16]
        mov     rcx, qword ptr [rbx + 24]
        call    DrvTarget
        movzx eax, al
        rol     r13, 5
        xor     r13, rax
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvSysvF0S32(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        mov     rdi, qword ptr [rbx + 0]
        mov     rsi, qword ptr [rbx + 8]
        mov     rdx, qword ptr [rbx + 16]
        mov     rcx, qword ptr [rbx + 24]
        call    DrvTarget
        movsxd rax, eax
        rol     r13, 5
        xor     r13, rax
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvSysvF0None(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        mov     rdi, qword ptr [rbx + 0]
        mov     rsi, qword ptr [rbx + 8]
        mov     rdx, qword ptr [rbx + 16]
        mov     rcx, qword ptr [rbx + 24]
        call    DrvTarget
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvSysvF1Xs(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        movq    xmm0, qword ptr [rbx + 0]
        mov     rdi, qword ptr [rbx + 8]
        mov     rsi, qword ptr [rbx + 16]
        mov     rdx, qword ptr [rbx + 24]
        call    DrvTarget
        movd eax, xmm0
        rol     r13, 5
        xor     r13, rax
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvSysvF1Rax(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        movq    xmm0, qword ptr [rbx + 0]
        mov     rdi, qword ptr [rbx + 8]
        mov     rsi, qword ptr [rbx + 16]
        mov     rdx, qword ptr [rbx + 24]
        call    DrvTarget
        rol     r13, 5
        xor     r13, rax
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvSysvF1Xd(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    r12
        push    r13
        push    rdi
        push    rsi
        mov     rbx, rcx
        mov     r12, rdx
        xor     r13d, r13d
@@dh:
        movq    xmm0, qword ptr [rbx + 0]
        mov     rdi, qword ptr [rbx + 8]
        mov     rsi, qword ptr [rbx + 16]
        mov     rdx, qword ptr [rbx + 24]
        call    DrvTarget
        movq rax, xmm0
        rol     r13, 5
        xor     r13, rax
        add     rbx, 32
        dec     r12
        jnz     @@dh
        mov     rax, r13
        pop     rsi
        pop     rdi
        pop     r13
        pop     r12
        pop     rbx
        ret
end;

function DrvMsF1Xd(P: Pointer; N: NativeInt): NativeUInt; ms_abi_default; assembler; nostackframe;
asm
        push    rbx
        push    rsi
        push    rdi
        sub     rsp, 32
        mov     rbx, rcx
        mov     rsi, rdx
        xor     edi, edi
@@dh:
        mov     rcx, qword ptr [rbx]
        mov     rdx, qword ptr [rbx + 8]
        mov     r8, qword ptr [rbx + 16]
        mov     r9, qword ptr [rbx + 24]
        movq    xmm0, rcx
        call    DrvTarget
        movq rax, xmm0
        rol     rdi, 5
        xor     rdi, rax
        add     rbx, 32
        dec     rsi
        jnz     @@dh
        mov     rax, rdi
        add     rsp, 32
        pop     rdi
        pop     rsi
        pop     rbx
        ret
end;

end.
