#!/usr/bin/env python3
"""Generate the deliberately wide local-variable pressure cases."""

from __future__ import annotations

from pathlib import Path


COUNT = 100
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "local-pressure" / "local_pressure_cases.inc"


def names(prefix: str) -> list[str]:
    return [f"{prefix}{index:03d}" for index in range(1, COUNT + 1)]


STRINGS = names("S")
BUFFERS = names("B")
PLAINS = names("P")


def declaration(items: list[str], type_name: str) -> list[str]:
    return [f"  {name}: {type_name};" for name in items]


def procedure(name: str, groups: list[tuple[list[str], str]], body: list[str]) -> list[str]:
    result = [f"procedure {name};", "var"]
    for items, type_name in groups:
        result.extend(declaration(items, type_name))
    result.append("begin")
    result.extend(f"  {line}" for line in body)
    result.extend(["end;", ""])
    return result


def assignments(items: list[str], source: str) -> list[str]:
    return [f"{name} := {source}[{index}];" for index, name in enumerate(items)]


def sum_strings(items: list[str]) -> list[str]:
    return [f"Local := Local + UInt64(Length({name}));" for name in items]


def sum_buffers(items: list[str]) -> list[str]:
    return [f"Local := Local + UInt64(Length({name}));" for name in items]


def sum_plains(items: list[str]) -> list[str]:
    return [f"Local := Local + {name};" for name in items]


def used_body(
    use_strings: bool,
    use_buffers: bool,
    use_plains: bool,
) -> list[str]:
    result: list[str] = []
    if use_strings:
        result.extend(assignments(STRINGS, "SourceStrings"))
    if use_buffers:
        result.extend(assignments(BUFFERS, "SourceBuffers"))
    if use_plains:
        result.extend(assignments(PLAINS, "SourcePlain"))
    result.append("Local := 0;")
    if use_strings:
        result.extend(sum_strings(STRINGS))
    if use_buffers:
        result.extend(sum_buffers(BUFFERS))
    if use_plains:
        result.extend(sum_plains(PLAINS))
    result.append("Sink := Sink + Local;")
    return result


def generate() -> str:
    string_group = [(STRINGS, "UnicodeString")]
    buffer_group = [(BUFFERS, "TBytes")]
    plain_group = [(PLAINS, "UInt64")]
    mixed_groups = string_group + buffer_group + plain_group

    lines = [
        "{ Generated by ../tools/generate_local_pressure.py. Do not edit manually. }",
        "",
        "procedure CaseEmpty;",
        "begin",
        "end;",
        "",
    ]
    lines.extend(procedure("CaseUnusedPlain100", plain_group, []))
    lines.extend(procedure("CaseUnusedStrings100", string_group, []))
    lines.extend(procedure("CaseUnusedBuffers100", buffer_group, []))
    lines.extend(procedure("CaseUnusedMixed300", mixed_groups, []))
    lines.extend(
        procedure(
            "CaseUsedPlain100",
            plain_group + [(["Local"], "UInt64")],
            used_body(False, False, True),
        )
    )
    lines.extend(
        procedure(
            "CaseUsedStrings100",
            string_group + [(["Local"], "UInt64")],
            used_body(True, False, False),
        )
    )
    lines.extend(
        procedure(
            "CaseUsedBuffers100",
            buffer_group + [(["Local"], "UInt64")],
            used_body(False, True, False),
        )
    )
    lines.extend(
        procedure(
            "CaseUsedMixed300",
            mixed_groups + [(["Local"], "UInt64")],
            used_body(True, True, True),
        )
    )
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(generate(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
