program devil;

{ Generated by scripts/generate_devil.py.  One seed, one program. }

{$ifdef FPC}
  {$mode delphiunicode}{$H+}
  {$modeswitch advancedrecords}
  {$modeswitch anonymousfunctions}
  {$modeswitch functionreferences}
  {$modeswitch INLINEVARS}
{$endif}
{$APPTYPE CONSOLE}
{$Q-}{$R-}

uses
{$ifdef FPC}
  {$ifdef UNIX}cthreads,{$endif}
{$endif}
  SysUtils, Classes, Math, TypInfo, Rtti, devil_runtime, devil_gen_unit;

{$I devil_support.inc}
{$I devil_expr.inc}
{$I devil_unary.inc}
{$I devil_fold.inc}
{$I devil_cmp.inc}
{$I devil_life.inc}
{$I devil_abi.inc}
{$I devil_float.inc}
{$I devil_str.inc}
{$I devil_disp.inc}
{$I devil_gen.inc}
{$I devil_arr.inc}
{$I devil_unit.inc}
{$I devil_chk.inc}
{$I devil_thr.inc}
{$I devil_set.inc}
{$I devil_rtti.inc}
{$I devil_flow.inc}
{$I devil_i128.inc}
{$I devil_lang.inc}

begin
  { Delphi Win64 masks every floating point exception by default while FPC
     leaves exInvalidOp unmasked; the forms under test must see one and the
     same environment on both. }
  SetExceptionMask([exInvalidOp, exDenormalized, exZeroDivide, exOverflow,
    exUnderflow, exPrecision]);
  RunDevilExprLayer;
  RunDevilUnaryLayer;
  RunDevilFoldLayer;
  RunDevilCmpLayer;
  RunDevilLifeLayer;
  RunDevilAbiLayer;
  RunDevilFloatLayer;
  RunDevilStrLayer;
  RunDevilDispLayer;
  RunDevilGenLayer;
  RunDevilArrLayer;
  RunDevilUnitLayer;
  RunDevilChkLayer;
  RunDevilThrLayer;
  RunDevilSetLayer;
  RunDevilRttiLayer;
  RunDevilFlowLayer;
  RunDevilI128Layer;
  RunDevilLangLayer;
  Halt(DevilReport('DEVIL', 2));
end.
