program devil;

{ Generated by scripts/generate_devil.py.  One seed, one program. }

{$ifdef FPC}
  {$mode delphiunicode}{$H+}
  {$modeswitch advancedrecords}
  {$modeswitch anonymousfunctions}
  {$modeswitch functionreferences}
  {$modeswitch INLINEVARS}
{$endif}
{$APPTYPE CONSOLE}
{ chains nest dozens of frames deep and each frame carries managed locals:
   the default stack is not the property under test, so it is raised }
{$ifdef FPC}
  {$M 268435456}
{$else}
  {$MAXSTACKSIZE 268435456}
{$endif}
{$Q-}{$R-}

uses
{$ifdef FPC}
  { the build driver pins this unit and requires it first; Delphi has no
     equivalent and manages its own heap }
  mormot.core.fpcx64mm,
  {$ifdef UNIX}cthreads,{$endif}
{$endif}
  SysUtils, Classes, Math, Variants, TypInfo, Rtti, devil_runtime;

{$I devil_support.inc}
{$I devil_gen.inc}

begin
  { Delphi Win64 masks every floating point exception by default while FPC
     leaves exInvalidOp unmasked; the forms under test must see one and the
     same environment on both. }
  SetExceptionMask([exInvalidOp, exDenormalized, exZeroDivide, exOverflow,
    exUnderflow, exPrecision]);
  WriteLn('DEVIL_LAYERS gen');

  DevilLayerBegin('gen');
  RunDevilGenLayer;
  DevilLayerEnd;
  { the instrument checks itself: the accumulator must have moved, and the
     number of feeds must be in the range the generator wrote }
  WriteLn('DEVIL_FEEDS ', DevilFeedCount);
  WriteLn('DEVIL_STEPS ', DevilStepCount);
  If DevilFeedCount = 0 then
    DevilCheckU('devil-bloodstream-alive', 0, 1);
  { порядковый канал есть не в каждом наборе слоёв: требовать шагов
     безусловно значит краснеть там, где их нет по построению.  Сравнение
     числа шагов между сборками делает гейт, и оно работает всегда. }
  Halt(DevilReport('DEVIL', 24));
end.
