#!/usr/bin/env python3
"""Generate branch_pad_relax.dpr: loops whose back-edge distance sweeps the
short-jump limit (127 bytes) with several conditional branches inside.

The branch pads inserted by the internal assembler (code placement rule R4,
doc-int/RTL_PROFILE_STAND_20260914.md) move code between a short backward
jump and its target after the jump encoding was chosen; the assembler must
then re-encode the jump as near.  Each base body (B branches) is repeated
with 0..EXTRA tail statements of two to five bytes that the optimizer
does not fold, so the back-edge distance walks across the limit in small
steps.  Loops with conditional branches inside get their back-edge from
the near estimate of the first assembler pass, so a second family of
straight-line loops with calls (no forward jumps) is generated: their
back-edge is short from the first pass on and a call pad inside forces the
near encoding.  The program prints one digest so that every optimization
level must agree.

Regenerate with:  python gen_branch_pad_relax.py > branch_pad_relax.dpr
"""

from __future__ import annotations

BASES = (2, 3, 4)         # conditional statements per loop body
EXTRA = 20                # tail statements, two to five bytes each
VARIANTS = 4              # statement orders per body size: different
                          # boundary crossings, so some loop of every size
                          # gets a pad inside
# tail statements that the optimizer does not fold into each other
TAIL = ("shl", "mul3", "xor8", "shl", "xor32", "mul3")


def tail_statement(kind: str, e: int) -> str:
    if kind == "shl":
        return "    Result := Result shl 1;"
    if kind == "mul3":
        return "    Result := Result * 3;"
    if kind == "xor8":
        return f"    Result := Result xor {17 + e};"
    return f"    Result := Result xor {70000 + e};"


def loop(index: int, branches: int, extra: int, variant: int) -> str:
    lines = [
        f"function Loop{index}(N: Integer): Cardinal;",
        "var",
        "  I: Integer;",
        "begin",
        "  Result := 0;",
        "  for I := 0 to N - 1 do",
        "  begin",
    ]
    for s in range(branches):
        k = (index + s + variant) % 3
        if k == 0:
            lines.append(f"    If Data[(I + {s}) and 255] > {index * 3 + s} then Inc(Result);")
        elif k == 1:
            lines.append(f"    If Data[(I + {s}) and 255] < {1000 + index + s} then Result := Result xor {index + 1};")
        else:
            lines.append(f"    If (I and {1 << (s % 4)}) <> 0 then Result := Result + Cardinal(Data[(I + {s}) and 255]);")
    for e in range(extra):
        lines.append(tail_statement(TAIL[(e + variant) % len(TAIL)], e))
    lines += ["  end;", "end;", ""]
    return "\n".join(lines)


CALL_BASES = (2, 3, 4)    # calls per straight-line loop body


def call_loop(index: int, calls: int, extra: int, variant: int) -> str:
    """A loop without forward jumps: its back-edge is short from the first
    assembler pass on, so a call pad inside the body is what pushes it past
    the limit and forces the near encoding."""
    lines = [
        f"function CallLoop{index}(N: Integer): Cardinal;",
        "var",
        "  I: Integer;",
        "begin",
        "  Result := 0;",
        "  for I := 0 to N - 1 do",
        "  begin",
    ]
    for c in range(calls):
        lines.append(f"    Result := Result + Cardinal(Data[(I + {c + variant}) and 255]);")
        lines.append(f"    Touch(Result xor {index + c});")
    for e in range(extra):
        lines.append(tail_statement(TAIL[(e + variant) % len(TAIL)], e))
    lines += ["  end;", "end;", ""]
    return "\n".join(lines)


def main() -> None:
    out = [
        "program branch_pad_relax;",
        "",
        "{ Generated by gen_branch_pad_relax.py; see that file.  Do not edit. }",
        "",
        "{$mode delphi}{$H+}{$Q-}{$R-}",
        "",
        "var",
        "  Data: array[0..255] of Integer;",
        "  Sink: Cardinal;",
        "",
        "procedure Touch(V: Cardinal); noinline;",
        "begin",
        "  Sink := Sink xor V;",
        "end;",
        "",
    ]
    count = 0
    for base in BASES:
        for extra in range(EXTRA + 1):
            for variant in range(VARIANTS):
                out.append(loop(count, base, extra, variant))
                count += 1
    calls_count = 0
    for base in CALL_BASES:
        for extra in range(EXTRA + 1):
            for variant in range(VARIANTS):
                out.append(call_loop(calls_count, base, extra, variant))
                calls_count += 1
    out += [
        "var",
        "  I: Integer;",
        "  Digest: Cardinal;",
        "begin",
        "  for I := 0 to 255 do",
        "    Data[I] := (I * 37 + 11) and 2047;",
        "  Digest := 0;",
    ]
    for i in range(count):
        out.append(f"  Digest := Digest * 31 + Loop{i}(300 + {i});")
    for i in range(calls_count):
        out.append(f"  Digest := Digest * 31 + CallLoop{i}(200 + {i});")
    out += [
        "  Digest := Digest * 31 + Sink;",
        "  WriteLn('BRANCH_PAD_RELAX:', Digest);",
        "end.",
    ]
    print("\n".join(out))


if __name__ == "__main__":
    main()
