#!/usr/bin/env python3
"""Gate for code placement rule R4 in the internal x86-64 assembler.

The code placement draft is off by default (doc/OPTIMIZER.md, "Code
placement"); the gate switches it on for its builds (MOONCOMPILER_PLACEMENT=1).
Proves on branch_pad_relax.dpr (generated by gen_branch_pad_relax.py) that

* `-O3` (CODEALIGN on) compiles although branch pads push short backward
  jumps past the 127-byte limit: the assembler re-encodes them as near and
  reports `jumps forced near` > 0 with `-vd`;
* `-O3`, `-O2` and `-O3 -OoNOCODEALIGN` print the same digest;
* the `-O3` executable satisfies the asserted placement rules on the fixture's
  procedures (check_placement_rules.py, needs objdump): R4 branch boundaries,
  feasible R2E and R3L loop placement, R2X useful prefixes, R3H loop heads,
  RT taken targets and R1 procedure entries. R2 and R3 are reported as
  diagnostic targets, not asserted;
* the padded executable stays within a coarse size guard of the unpadded one;
* the relaxation settles well before the assembler's pass limit (at most 32 of
  the 64 passes it allows; the fixture needs 6-8 on Win64 and 12-15 on Linux).

The gate switches the draft on, so missing relaxation statistics is a failure.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SOURCE = HERE / "branch_pad_relax.dpr"
TOOLS = ROOT / "qualification" / "performance" / "tools"
sys.path.insert(0, str(TOOLS))

import code_placement  # noqa: E402

STATS = re.compile(r"Code placement: branch pads (\d+), jumps forced near (\d+), relaxation passes (\d+)")
# half of the assembler's RelaxPassLimit: measured 6-8 on Win64 and 12-15 on Linux
PASS_CEILING = 32
PADBYTES = re.compile(r"pad bytes as prefixes (\d+), as nops (\d+) \(dead (\d+)\)")


def default_compiler() -> Path:
    if os.name == "nt":
        return ROOT / "toolchain/bin/x86_64-win64/ppcx64.exe"
    return ROOT / "toolchain/bin/ppcx64"


def default_rtl() -> Path:
    if os.name == "nt":
        return ROOT / "toolchain/units/x86_64-win64/rtl"
    roots = sorted((ROOT / "toolchain/lib/fpc").glob("*/units/x86_64-linux/rtl"))
    if len(roots) != 1:
        raise SystemExit("cannot uniquely locate Linux RTL; pass --rtl")
    return roots[0]


def link_args() -> list[str]:
    if os.name == "nt":
        return []
    probe = subprocess.run(["gcc", "-print-file-name=libgcc_s.so"], capture_output=True, text=True, timeout=30)
    libgcc = Path(probe.stdout.strip())
    if probe.returncode != 0 or not libgcc.is_absolute() or not libgcc.exists():
        raise SystemExit("cannot locate libgcc_s")
    return [f"-Fl{libgcc.parent}"]


def compile_one(compiler: Path, rtl: Path, name: str, options: list[str], outdir: Path) -> tuple[Path, str]:
    target = outdir / name
    target.mkdir(parents=True, exist_ok=True)
    cmd = [str(compiler), "-Mdelphi", "-n", "-gw3", "-vd", "-dMOONCOMPILER_VANILLA_RUNTIME",
           f"-Fu{rtl}", f"-FE{target}", f"-FU{target}", f"-o{name}"] + link_args() + options + [str(SOURCE)]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300,
                          env={**os.environ, "MOONCOMPILER_PLACEMENT": "1"})  # the draft is off by default
    output = (proc.stdout or "") + (proc.stderr or "")
    exe = target / name
    if not exe.is_file():
        exe = target / (name + ".exe")
    if proc.returncode != 0 or not exe.is_file():
        diagnostics = [line for line in output.splitlines()
                       if re.search(r"Error|Fatal|Warning|Code placement", line)]
        raise RuntimeError(f"compile failed ({name})\n" + "\n".join(diagnostics[-30:]))
    return exe, output


def run(exe: Path) -> tuple[int, str]:
    proc = subprocess.run([str(exe)], capture_output=True, text=True, timeout=60)
    return proc.returncode, proc.stdout.strip()


def placement_check(exe: Path) -> tuple[int, str]:
    cmd = [sys.executable, str(TOOLS / "check_placement_rules.py"), str(exe),
           "--match", r"P\$BRANCH_PAD_RELAX", "--assert", "R4,R2E,R2X,R3H,R3L,RT,R1", "--list-violations"]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--compiler", type=Path, default=default_compiler())
    ap.add_argument("--rtl", type=Path)
    ap.add_argument("--keep", action="store_true", help="keep the build directory")
    args = ap.parse_args()
    args.rtl = args.rtl or default_rtl()

    failures: list[str] = []
    notes: list[str] = []
    tmp = Path(tempfile.mkdtemp(prefix="optimizer_branch_pad_"))
    try:
        builds = {"o3": ["-O3"], "o2": ["-O2"], "o3_off": ["-O3", "-OoNOCODEALIGN"],
                  "o3_dbg": ["-O3", "-gw3"]}
        results: dict[str, tuple[Path, str]] = {}
        outputs: dict[str, tuple[int, str]] = {}
        for name, options in builds.items():
            try:
                results[name] = compile_one(args.compiler, args.rtl, name, options, tmp)
                outputs[name] = run(results[name][0])
            except Exception as exc:
                failures.append(f"{name}: {exc}")
        if len(results) == len(builds):
            digests = {name: out for name, (_, out) in outputs.items()}
            if any(code != 0 for code, _ in outputs.values()) or len(set(digests.values())) != 1 \
                    or not digests["o3"].startswith("BRANCH_PAD_RELAX:"):
                failures.append(f"digests differ or a run failed: {outputs!r}")
            else:
                notes.append(f"digest {digests['o3']}")
            stats = STATS.search(results["o3"][1])
            if stats:
                pads, forced, passes = (int(x) for x in stats.groups())
                notes.append(f"o3: branch pads {pads}, jumps forced near {forced}, relaxation passes {passes}")
                if pads == 0:
                    failures.append("o3: the assembler inserted no branch pad")
                if forced == 0:
                    failures.append("o3: no short jump was forced near, the fixture does not reach the edge")
                # The layout must settle well before the assembler's own pass limit
                # (RelaxPassLimit = 64, where every pad freezes where it stands).  How many
                # passes this fixture needs depends on the ABI: 6-8 on Win64, 12-15 on Linux,
                # where the SysV frames give the pads more room to move each other.  The
                # ceiling catches a layout that stopped converging, not the difference
                # between the two.
                if passes > PASS_CEILING:
                    failures.append(f"o3: relaxation needed {passes} passes of the {PASS_CEILING} "
                                    "allowed here, the layout does not converge")
                padbytes = PADBYTES.search(results["o3"][1])
                if not padbytes:
                    failures.append("o3: no pad byte statistics: the pads are not realized as prefixes")
                else:
                    prefixes, nops, dead = (int(x) for x in padbytes.groups())
                    live = nops - dead
                    notes.append(f"o3: pad bytes as prefixes {prefixes}, as nops {nops} (dead {dead})")
                    if prefixes == 0:
                        failures.append("o3: no pad byte went onto an instruction as a prefix")
                    if live * 4 > prefixes + live:
                        failures.append(
                            f"o3: {live} executed nop bytes against {prefixes} prefix bytes: "
                            "more than a quarter of the executed padding is nops")
                padbytes_dbg = PADBYTES.search(results["o3_dbg"][1])
                if not padbytes_dbg:
                    failures.append("o3_dbg: no pad byte statistics with -gw3")
                else:
                    prefixes_dbg, nops_dbg, dead_dbg = (int(x) for x in padbytes_dbg.groups())
                    live_dbg = nops_dbg - dead_dbg
                    notes.append(f"o3_dbg (-gw3): pad bytes as prefixes {prefixes_dbg}, as nops {nops_dbg} (dead {dead_dbg})")
                    if live_dbg * 4 > prefixes_dbg + live_dbg:
                        failures.append(
                            f"o3_dbg: {live_dbg} executed nop bytes against {prefixes_dbg} prefix bytes with -gw3: "
                            "debug line labels must not cut the prefix window")
            else:
                failures.append(
                    "o3: no placement statistics line (-vd); "
                    "the code placement draft is off"
                )
            stats_off = STATS.search(results["o3_off"][1])
            if stats_off and int(stats_off.group(1)) != 0:
                failures.append("o3_off: branch pads inserted although CODEALIGN is off")
            code, report = placement_check(results["o3"][0])
            tail = "\n".join(report.strip().splitlines()[1:10])
            notes.append("placement gate:\n" + tail)
            if code != 0:
                failures.append(
                    "o3: placement violations in the padded executable\n"
                    + report[-2000:]
                )
            instructions = code_placement.disassemble(results["o3"][0])
            too_long = [
                (address, mnemonic, len(raw))
                for address, (mnemonic, _, raw) in instructions.items()
                if len(raw) > 15
            ]
            if too_long:
                failures.append(
                    "o3: padding emitted x86 instructions longer than 15 bytes: "
                    + repr(too_long[:10])
                )
            longest_padded = max(
                (
                    len(raw)
                    for _, _, raw in instructions.values()
                    if raw and raw[0] == 0x3E
                ),
                default=0,
            )
            notes.append(f"longest DS-padded instruction {longest_padded} bytes")
            base = results["o3_off"][0].stat().st_size
            padded = results["o3"][0].stat().st_size
            notes.append(f"size o3_off {base} -> o3 {padded} ({(padded / base - 1) * 100:+.2f}%)")
            if padded > base * 1.10:
                failures.append(f"o3: executable grew by more than 10% ({base} -> {padded})")
    finally:
        if args.keep:
            print(f"build directory kept: {tmp}")
        else:
            shutil.rmtree(tmp, ignore_errors=True)

    for note in notes:
        print(" -", note)
    if failures:
        print(f"BRANCH PAD GATE: FAIL ({len(failures)} problems)")
        for failure in failures:
            print(" *", failure)
        return 1
    print("BRANCH PAD GATE: PASS (compiles past the short-jump edge, equal digests, rules R4/R2E/R2X/R3H/R3L/RT/R1 clean, size)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
